### ISSUE TITLE
updated mode-decomposition tutorial

### ISSUE THREAD

**Issue by stevengj** [NanoComp/meep#1011]
As discussed with @oskooi, it would be nice to do an updated version of https://meep.readthedocs.io/en/latest/Python_Tutorials/Mode_Decomposition/#transmittance-spectra-for-planewave-at-normal-incidence that shows the results as a function of period, in order to see the deviations from scalar-diffraction theory.

In particular, you could plot the transmitted power in the 0-th diffraction order as a function of period, showing:

1. For period >> λ, it matches scalar diffraction theory (is ≈ 0 for this structure).
2. For period << λ, it goes to the effective medium limit of transmission through a 3 layer structure (a layer of the mean ε (weighted by the duty cycle) sandwiched between the high and low ε).
3. In between, there is a (continuous) transition region where a full-wave calculation is required.

**Comment by oskooi** [comment]
> If you plot it for more intermediate periodicities, then if it is a real effect then you will see continuous oscillations in the transmittance.

&mdash; @stevengj 

![binary_grating_scalar_theory_vs_meep](https://user-images.githubusercontent.com/7152530/64371817-5bb43b00-cfd6-11e9-94df-ddd0b37a556e.png)

**Comment by stevengj** [comment]
You could also show the polarization dependence (Ez vs. Hz) for normal incidence.  In the large-period (scalar diffraction) regime, there is no difference.   In the period << λ (effective medium) regime, the Ez polarization sees the average ε but the Hz polarization sees 1/(average 1/ε) in the periodic region.

**Comment by oskooi** [comment]
Shown below is a plot of the transmittance of the 0-th diffraction order vs. grating periodicity in the range `0.1`-`10` μm for an input planewave at normal incidence and λ=`0.5` μm (based on the [binary grating tutorial example](https://meep.readthedocs.io/en/latest/Python_Tutorials/Mode_Decomposition/#diffraction-spectrum-of-a-binary-grating)). The gradual transition from the sub-wavelength (transmittance: `1.0`) to the scalar diffraction (transmittance: `0`) regime is evident in the range `0.1`-`2.0` μm.

![0th_order_vs_gp](https://user-images.githubusercontent.com/7152530/64469575-5c89c180-d0e9-11e9-8b8f-700f591d7de5.png)

Note: the "kink" in the plot at a periodicity of `0.9` μm does *not* seem to be a discretization artifact since it is present for both `resolution` datasets: `100` and `200` (i.e., doubling the `resolution` has no effect).

In the subwavelength regime, the transmittance is `1.0` for *both* polarizations as computed from the transfer-matrix formulation for the 3-layer structure:

```
import cmath
import numpy as np

wvl = 0.5              # wavelength (um)                                                                                                                                  
gp = 10.0              # grating period (um)                                                                                                                                   
gh = 0.5               # grating height (um)                                                                                                                         
gdc = 0.5              # grating duty cycle                                                                                                                               
nglass = 1.5
nair = 1

# average index for out-of-plane (Ez) polarization                                                                                                                        
neff = gdc*nglass + (1-gdc)*nair

# average index for in-plane (Hz) polarization                                                                                                                            
# neff = 1/(1/(gdc*nglass) + 1/((1-gdc)*nair))                                                                                                                            

rs = lambda n1,n2: (n1-n2)/(n1+n2)

ts = lambda n1,n2: 2*n1/(n1+n2)

kwav = lambda wvl,n: 2*cmath.pi/(wvl/n)

## field propagation in a layer of index n1 of length d followed by transmission into a layer of index n2                                                                 
## Eq. (11) of "Multilayer optical calculations" by Steven J. Byrnes, https://arxiv.org/pdf/1603.02720.pdf                                                                
Mlayer = lambda n1,n2,d: np.array([[cmath.exp(-1j*d*kwav(wvl,n1)),0], [0,cmath.exp(1j*d*kwav(wvl,n1))]]) * np.array([[1,rs(n1,n2)], [rs(n1,n2),1]]) * 1/ts(n1,n2)

## Eq. (13) of ibid                                                                                                                                                       
Mtot = np.array([[1,rs(nglass,neff)], [rs(nglass,neff),1]]) * Mlayer(neff,nair,gh) * 1/ts(nglass,neff)

## Eq. (15) of ibid                                                                                                                                                       
R = abs(Mtot[1,0]/Mtot[0,0])**2

print("tran: {}".format(1-R))
```

Next steps:

1. Demonstrate polarization-*dependent* results in the subwavelength regime (i.e., transmittance ≠`1`) by increasing the index contrast?

2. Show the transition regime of `0.1`-`2.0` μm clearly using more intermediate periodicities.

**Comment by oskooi** [comment]
Plot of the transmittance vs. periodicity for the two polarizations. The polarization-dependence is weak and does not change with increasing index contrast or varying the grating layer thickness.

![0th_order_vs_gp_Ez_Hz](https://user-images.githubusercontent.com/7152530/64479650-bd0f1200-d16e-11e9-9c86-057baef10548.png)
