### ISSUE TITLE
Propagation of a plane wave in a 3D structure

### ISSUE THREAD

**Issue by khashabri** [NanoComp/meep#1046]
Hi guys,
the following code animates how a plane wave propagates in an empty 3D cell. In the first two plots, the wave is Ey polarized. The problem is, it is expected to observe a plane wave structure no matter which 2D slice (xy, xz or yz) is chosen. However, only the first plot shows a complete appropriate course.

```
import meep as mp
import matplotlib.pyplot as plt
cell_len = 5


def anim_plane_wave(polarization, plane, title):
    resolution = 5
    dpml = 1

    pml_layers = [mp.PML(thickness=dpml)]
    cell_size = mp.Vector3(cell_len, cell_len, cell_len)
    source_com = polarization

    sources = [mp.Source(mp.GaussianSource(1, fwidth=0.25),
                         center=mp.Vector3(dpml - cell_len/2),
                         size=mp.Vector3(0, cell_len, cell_len),
                         component=source_com)]

    sim = mp.Simulation(resolution=resolution,
                        cell_size=cell_size,
                        boundary_layers=pml_layers,
                        sources=sources,
                        k_point=mp.Vector3())

    output_plane = mp.Volume(center=mp.Vector3(), size=mp.Vector3(plane[0], plane[1], plane[2]))
    anim = mp.Animate2D(sim,
                        fields=source_com,
                        normalize=True,
                        output_plane=output_plane,
                        realtime=True)

    sim.run(mp.at_every(1, anim), until=20)
    sim.plot2D(output_plane=output_plane,fields=source_com)
    plt.savefig('plane_wave_{:}.png'.format(title))
    plt.close()

if __name__ == '__main__':
    anim_plane_wave(polarization=mp.Ey, plane=[cell_len, 0, cell_len], title='Ey_xz')
    anim_plane_wave(polarization=mp.Ey, plane=[cell_len, cell_len, 0], title='Ey_xy')
    anim_plane_wave(polarization=mp.Ez, plane=[cell_len, 0, cell_len], title='Ez_xz')
    anim_plane_wave(polarization=mp.Ez, plane=[cell_len, cell_len, 0], title='Ez_xy')
```

**_Ey source being observed in the x-z plane_** 
![plane_wave_Ey_xz](https://user-images.githubusercontent.com/50481847/67876773-b8e0ee80-fb38-11e9-9a66-91b82b46e427.png)
This seems to be correct.

_**Ey source being observed in the x-y plane**_
![plane_wave_Ey_xy](https://user-images.githubusercontent.com/50481847/67876796-c4ccb080-fb38-11e9-8b8a-17134c3c0717.png)
Outside of PML, it seems to be right. But, why doesn't it look like the first figure?

**_Ez source being observed in the x-z plane_** 
![plane_wave_Ez_xz](https://user-images.githubusercontent.com/50481847/67876967-0f4e2d00-fb39-11e9-85cf-fbe1bd6fb639.png)
Analogous to the previous plot.

**_Ez source being observed in the x-y plane_** 
![plane_wave_Ez_xy](https://user-images.githubusercontent.com/50481847/67876985-17a66800-fb39-11e9-94b2-943b42bef7c0.png)
Strange! It is expected to get a figure like in the first case.

**Comment by oskooi** [comment]
You are using a `GaussianSouce` and showing a snapshot of the fields at some arbitrary time (`t=20`) where the fields from the planewave pulse have likely fully decayed away (due to absorption from the PML). If you replace `GaussianSource` with `ContinuousSource`, you will see the planewave field profile.

PS. as mentioned [previously](https://github.com/NanoComp/meep/issues/1040#issuecomment-545223632), the meep-discuss mailing list is a better place for usage questions.

**Comment by khashabri** [comment]
@oskooi I consider this as a bug rather than a usage question. At the moment that the figures are captured, the source is still on. Even though, there must be a symmetry/similarity between the first `(Ey xz-plane)` and the fourth `(Ez xy-plane)` plot. It is basically the same simulation just on another axis. This means everything has just been rotated. 

Just to make sure, I've also replaced the `GaussianSource` with a `ContinuousSource`:
```
sources = [mp.Source(mp.ContinuousSource(frequency=1),
                 center=mp.Vector3(dpml - cell_len/2),
                 size=mp.Vector3(0, cell_len, cell_len),
                 component=source_com)]
```
and there is **no** difference in the previously presented profiles regarding to their planarity. So, there must be either something wrong with the PML or the source implementations, cause it is not clear why the fields are not planar, and also without any symmetry and similarity after rotations, in such a simple configuration.
By the way, the code actually animates the whole problem. The presented _snapshots_ are only to make people curious to have a look at this fundamental issue.

**Comment by oskooi** [comment]
In your setup, the PML surrounds the entire cell and therefore overlaps the planewave source in the *y* and *z* directions which causes a distortion in the planar wavefronts. If you only include PML in the direction of propagation (i.e., *x*), via `pml_layers = [mp.PML(thickness=dpml,direction=mp.X)]` then the planewave profile is evident.

**Ey source being observed in the x-z plane**

![plane_wave_Ey_xz](https://user-images.githubusercontent.com/7152530/67970668-972f4800-fbc8-11e9-8b23-161f4a3e87ec.png)

**Ey source being observed in the x-y plane**

![plane_wave_Ey_xy](https://user-images.githubusercontent.com/7152530/67970648-90a0d080-fbc8-11e9-940f-7c750be6be00.png)

**Ez source being observed in the x-z plane**

![plane_wave_Ez_xz](https://user-images.githubusercontent.com/7152530/67970688-a1e9dd00-fbc8-11e9-89a7-4bf1e229b279.png)

**Ez source being observed in the x-y plane**

![plane_wave_Ez_xy](https://user-images.githubusercontent.com/7152530/67970682-9eeeec80-fbc8-11e9-8a6a-468a7b496342.png)

**Comment by stevengj** [comment]
It should be okay to have PML in the directions perpendicular to the planewave — in theory (in the exact Maxwell equations), PML should have no effect on a planewave propagating exactly parallel to the boundary.

Your `resolution=5` is awfully low, so maybe this is just a discretization effect?   I would try things in 2d first (i.e. a planewave in the x direction, with PML in both x and y), so that it is easier to run experiments with resolution.

**Comment by stevengj** [comment]
Ardavan tried it and it doesn't seem to be a resolution effect.   I suspect that there may be an issue with how we are introducing the current source J into the PML region — if you look at the version of PML that we use ([here](https://meep.readthedocs.io/en/latest/Perfectly_Matched_Layer/)), there are some Jacobian factors in the definition of the D field etc and we might need similar factors in our current sources in the PML region.

**Comment by oskooi** [comment]
As a reference, here is a 2d version of the test case from above.

```py
import meep as mp
import matplotlib.pyplot as plt

pml_layers = [mp.PML(thickness=1)]
cell_size = mp.Vector3(10,10)

sources = [mp.Source(mp.ContinuousSource(1),
                     center=mp.Vector3(-4),
                     size=mp.Vector3(y=10),
                     component=mp.Ez)]

sim = mp.Simulation(resolution=10,
                    cell_size=cell_size,
                    boundary_layers=pml_layers,
                    sources=sources,
                    k_point=mp.Vector3())

sim.run(until=30)

sim.plot2D(fields=mp.Ez)
plt.show()
```

![foo2](https://user-images.githubusercontent.com/7152530/68047469-b4811680-fc9b-11e9-8223-4b60d1d02bc1.png)

**Comment by stevengj** [comment]
In particular, looking at my [notes on coordinate transformations](https://math.mit.edu/~stevenj/18.369/coordinate-transform.pdf), when you transform Maxwell's equations with a Jacobian factor 𝒥, the current J is multiplied by a factor of 𝒥/det𝒥.   Comparing to our [PML description](http://math.mit.edu/~stevenj/papers/OskooiJo11.pdf), note that 𝒥/det𝒥=𝒮₁𝒮₂, so `∇×H=iωεE+J` gets transformed to `∇×H=iωD̃+𝒮₁𝒮₂J`.  Looking at the expression for D̃ on page 2373, if we pull out the 𝒮₁𝒮₂ factors then it seems that in the PML regions the J term should update the U auxiliary field (e.g. `f_u[Dx]` in the Meep source) rather than D (`f[Dx]`).

Hopefully, this should be a few-lines fix to the `step_current` function in `step.cpp`.    Note that the fields may still be transformed by a Jacobian factor in the PML region, but the planewave in the interior of the computational cell should converge to a true planewave (flat wavefronts, unlike the "wavy" fronts shown above that are indicative of some internal reflections) as we increase the resolution.

**Comment by oskooi** [comment]
Output for the `pmlcurrent` branch for the 2d test from above:

![foo2_pmlcurrent](https://user-images.githubusercontent.com/7152530/68050135-c1a10400-fca1-11e9-8194-19652018947b.png)

**Comment by stevengj** [comment]
Note that if you look at the equations, then an Ey source actually doesn't get transformed by a y PML, so Ey should be okay in the master branch (in the 2d case).

**Comment by oskooi** [comment]
Using the `pmlcurrent` branch, for an E<sub>y</sub> source and plotting the scalar H<sub>z</sub> fields, there are no fields.

```py
import meep as mp
import matplotlib.pyplot as plt

pml_layers = [mp.PML(thickness=1)]
cell_size = mp.Vector3(10,10)

sources = [mp.Source(mp.ContinuousSource(1),
                     center=mp.Vector3(-4),
                     size=mp.Vector3(y=10),
                     component=mp.Ey)]

sim = mp.Simulation(resolution=20,
                    cell_size=cell_size,
                    boundary_layers=pml_layers,
                    sources=sources,
                    k_point=mp.Vector3())

sim.run(until=30)

sim.plot2D(fields=mp.Hz)
plt.show()
```
![foo2_Ey](https://user-images.githubusercontent.com/7152530/68050412-5146b280-fca2-11e9-9163-82df0041bf58.png)

For the `master` branch, the wavefronts are exactly planar.

![foo2_Ey_master](https://user-images.githubusercontent.com/7152530/68050552-910d9a00-fca2-11e9-99df-61fc238d0f89.png)

**Comment by stevengj** [comment]
Looks like the `pmlcurrent` branch isn't quite right yet.    (I also need to be a bit careful because of the iω factor when putting the J term into the U update.)

**Comment by oskooi** [comment]
For the `master` branch, using an H<sub>y</sub> source and plotting E<sub>z</sub> produces wavefronts that are also planar.

![foo2_Hy](https://user-images.githubusercontent.com/7152530/68050721-02e5e380-fca3-11e9-8a20-91862a45c90a.png)

**Comment by stevengj** [comment]
Yes, in 2d this is a workaround: use a y-directed source for an x-directed planewave.  In 3d there is no workaround as far as I can tell—until we fix this—since no matter what source orientation you choose, the 𝒥/det𝒥 will be ≠ 1 for one of the two transverse PMLs.

**Comment by stevengj** [comment]
Actually, it looks like the `is_integrated` source, which adds the source term into a different place in the timestepping equations, might actually be doing the right thing in PML.

**Comment by oskooi** [comment]
Indeed, setting `is_integrated=True` generates a correct planewave in the PML.

```py
import meep as mp
import matplotlib.pyplot as plt

pml_layers = [mp.PML(thickness=1)]
cell_size = mp.Vector3(10,10)

sources = [mp.Source(mp.ContinuousSource(1,is_integrated=True),
                     center=mp.Vector3(-4),
                     size=mp.Vector3(y=10),
                     component=mp.Ez)]

sim = mp.Simulation(resolution=20,
                    cell_size=cell_size,
                    boundary_layers=pml_layers,
                    sources=sources,
                    k_point=mp.Vector3())

sim.run(until=30)

sim.plot2D(fields=mp.Ez)
plt.show()
```

![foo_Ez](https://user-images.githubusercontent.com/7152530/68263598-3b672380-fffb-11e9-8560-91f8927c5d5b.png)

Also works for the H<sub>z</sub>-polarized source.

**Comment by oskooi** [comment]
3d seems does *not* seem to be working.

```py
import meep as mp
import matplotlib.pyplot as plt

pml_layers = [mp.PML(thickness=1)]
cell_size = mp.Vector3(10,10,10)

sources = [mp.Source(mp.ContinuousSource(1,is_integrated=True),
                     center=mp.Vector3(-4),
                     size=mp.Vector3(0,10,10),
                     component=mp.Ez)]

sim = mp.Simulation(resolution=10,
                    cell_size=cell_size,
                    boundary_layers=pml_layers,
                    sources=sources,
                    k_point=mp.Vector3())

sim.run(until=30)

sim.plot2D(fields=mp.Ez,
           output_plane=mp.Volume(center=mp.Vector3(4),size=mp.Vector3(0,10,10)))
plt.show()
```

![foo3d](https://user-images.githubusercontent.com/7152530/68264060-846ba780-fffc-11e9-9c6d-e488ae509c35.png)

**Comment by stevengj** [comment]
Plotting the wrong slice?

**Comment by oskooi** [comment]
Taking a *xz* slice:

```py
import meep as mp
import matplotlib.pyplot as plt

pml_layers = [mp.PML(thickness=1)]
cell_size = mp.Vector3(10,10,10)

sources = [mp.Source(mp.ContinuousSource(1,is_integrated=True),
                     center=mp.Vector3(-4),
                     size=mp.Vector3(0,10,10),
                     component=mp.Ez)]

sim = mp.Simulation(resolution=10,
                    cell_size=cell_size,
                    boundary_layers=pml_layers,
                    sources=sources,
                    k_point=mp.Vector3())

sim.run(until=30)

sim.plot2D(fields=mp.Ez,
           output_plane=mp.Volume(center=mp.Vector3(y=2),size=mp.Vector3(10,0,10)))
plt.show()
```

![foo3d](https://user-images.githubusercontent.com/7152530/68264259-14115600-fffd-11e9-8492-41327fcf10f3.png)

**Comment by stevengj** [comment]
That looks fine — inside the PML we are seeing the fields rescaled by a Jacobian factor.  The important thing is to have planar wavefronts in the interior.

**Comment by oskooi** [comment]
In 2d, an E<sub>y</sub> source produces a similar effect.

```py
import meep as mp
import matplotlib.pyplot as plt

pml_layers = [mp.PML(thickness=1)]
cell_size = mp.Vector3(10,10)

sources = [mp.Source(mp.ContinuousSource(1,is_integrated=True),
                     center=mp.Vector3(-4),
                     size=mp.Vector3(y=10),
                     component=mp.Ey)]

sim = mp.Simulation(resolution=20,
                    cell_size=cell_size,
                    boundary_layers=pml_layers,
                    sources=sources,
                    k_point=mp.Vector3())

sim.run(until=30)

sim.plot2D(fields=mp.Ey)
plt.show()
```

![foo2d](https://user-images.githubusercontent.com/7152530/68264498-d2cd7600-fffd-11e9-8caa-7cb4d6e8ca97.png)

**Comment by stevengj** [comment]
Conclusion:

* In the short term, you'll need to manually set `is_integrated=True` for sources that extend into the PML.  We'll do this in the Mie scattering tutorial (#1045).

* In the longer term, we may want to automatically switch to `is_integrated=True` if we detect a source like this (i.e. one that extends the whole width of the cell into a PML).

* Would also be nice to add explanations of this effect, both the need for integrated sources and the Jacobian factor modifying the fields in the PML, in the PML documentation.

**Comment by smartalecH** [comment]
> (I went through the math a little bit more carefully, and I found that the correct thing was to add ε⁻¹∫J to the W update equation, and this is precisely what the integrated source does.)

@stevengj I've been thinking about this carefully, and I don't quite see why this works (obviously it does)... especially for a CW source, as is used in these examples.

The normal source term, $J$, is added to the $D$ fields, along with some weighting factor (e.g. $\Delta t$, $\sigma_D$, etc.) using [`step_source()`](https://github.com/NanoComp/meep/blob/abe31a91e05bbe43da46514df7011c10e169c164/src/step.cpp#L289-L318).

The `is_integrated` source term adds $\int J dt$ [to the `f_minus_p` term](https://github.com/NanoComp/meep/blob/b00f2d4ce20e683275a4895c8dc8318677a296d1/src/update_eh.cpp#L126-L139). But this appears to be the _same_ as adding it to the $D$ fields (since $D$ is the `f` in this case).

Obviously adding $\int J$ is not the same as adding $J$, _except_ in these cases, where the time dependence is just a sinusoid. So I must be missing something about the _order_ in which the `is_integrated` source is inserted into the update equations...

(I think we should more thoroughly document this, especially since the PML meep notes omit sources)

**Comment by oskooi** [comment]
See the related discussion in https://meep.readthedocs.io/en/latest/FAQ/#how-is-the-source-current-defined.

**Comment by smartalecH** [comment]
Thanks @oskooi. This discussion reiterates the integration of $J$, but doesn't discuss the impact of when $J$ is actually timestepped. In other words, the integral alone shouldn't be what solves the above issue.

**Comment by stevengj** [comment]
The effect of the integrated source is not on the update of E from D, but on the next timestep of *D*.

A non-integrated current source is added directly to the D field, which means it interacts with the next timestep of D, which multiplies the previous D field by some factor involving the PML:
<img width="483" alt="image" src="https://user-images.githubusercontent.com/2913679/198386153-0992e583-8934-4f8d-b481-9e659681fb4a.png">

An integrated current source, on the other hand, does *not* modify D directly.  Instead, it modifies the `d_minus_p` array, which stores D–P (subtracting all polarizations from materials or integrated sources), which is then used to update E as you noted.  But since the current is not included in the D array, it doesn't enter directly in the next timestep equation of D. 

If you go through the math of the PML, it turns out that the latter is the right thing to do.   (At least, that's what I recall doing, though I no longer recall the notes.  Obviously, it works empirically.)   It would be nice to update the PML notes to explain what happens to the source terms.

**Comment by smartalecH** [comment]
Thanks, @stevengj!
