### ISSUE TITLE
allow unequal DFT frequencies

### ISSUE THREAD

**Issue by stevengj** [NanoComp/meep#1070]
Right now all of the DFT objects use equally spaced frequency points.   It would be nice to be able to pass in an arbitrary array of frequencies instead.

For example, one could use Chebyshev nodes for the frequencies and then do high-order Chebyshev interpolation using the [barycentric formula](https://www.chebfun.org/docs/guide/guide04.html).   (Indeed, this is potentially so useful that we might want to build Chebyshev interpolation into Meep — it fits well with the "illusion of continuity" philosophy.  We could give the illusion of computing the spectrum continuously in a given range to a given order of interpolation accuracy.)

As another example, I recently worked out ["optimal" solar-weighted Gaussian quadrature rules](https://nbviewer.jupyter.org/urls/math.mit.edu/~stevenj/Solar-Quadrature.ipynb?flush_cache=true) for integrating against the solar irradiance spectrum.    This is useful for solar-cell simulations, and the optimal frequency evaluation points are unequally spaced.

**Comment by stevengj** [comment]
In terms of coding, basically what we need is to take functions like `dft_flux` and add a new method where instead of passing `double fmin, double fmax, int Nf` we pass `const double *f, int Nf` .

**Comment by stevengj** [comment]
Basically, these parameters need to be replaced by an array (or a `std::vector`) wherever they appear: https://github.com/NanoComp/meep/blob/5f2d84f11569fc1a0cf6ef3c563205d305d450b5/src/meep.hpp#L1012

**Comment by stevengj** [comment]
Now that the C interface supports taking a `std::vector<double> freqs` array, what's the best way to pass a NumPy array to this, @ChristopherHogan?

**Comment by ChristopherHogan** [comment]
Well, converting a python list to a std::vector would happen automatically (maybe requiring adding a vector type [here](https://github.com/NanoComp/meep/blob/master/python/meep.i#L1279)), but to convert a numpy array you would have to write a wrapper that creates a std::vector and copies the numpy array, then passes the vector on to C++. If the freqs arrays will be small, then adding a `.tolist()` to the numpy inputs would be the easiest. If the freqs arrays will be large, then it's nicer to pass it as a `*data, size` pair because it avoids the copy.

**Comment by ChristopherHogan** [comment]
To avoid making a copy of the `freqs` numpy array to a `std::vector` in the typemap, we would need to make an interface that sits below the current one that python could call. The new prototype would be, for example

```c++
dft_chunk *fields::add_dft_from_ptr(const volume_list *where, double *freq, int Nfreq, bool include_dV_and_interp_weights);
```

And the current interface would become

```c++
dft_chunk *fields::add_dft(const volume_list *where, const std::vector<double> freq, bool include_dV_and_interp_weights) {
   // NOTE: Assumes you'll never have a vector larger than ~ 2 billion freqs
    return add_dft_from_ptr(where, freq.data(), (int)freq.size(), include_dV_and_interp_weights);
}
```

Then, you can use the numpy typemaps to wrap `add_dft_from_ptr` like this

```c++
%apply (double* IN_ARRAY1, int DIM1) {(double* freqs, int Nfreq)}
```

You can use the SWIG `%rename` directive so that the python interface can call `add_dft_from_ptr` with a different name, if you want.

**Comment by stevengj** [comment]
If we go that route, might as well just add a `double *freq, size_t Nfreq` method to `add_dft`.

**Comment by oskooi** [comment]
Assuming that the freqs array is passed in as a numpy array and converted/copied to a list, how would the current [`add_flux`](https://github.com/NanoComp/meep/blob/master/python/simulation.py#L1818-L1821), [`add_near2far`](https://github.com/NanoComp/meep/blob/master/python/simulation.py#L1670-L1674), etc. interface need to be changed in order to accept either (`fcen`,`df`,`nfreq`) or `freqs` as positional rather than keyword arguments when Python does not support multiple dispatch? In the current interface, `fcen`,`df`,`nfreq` are positional arguments with no default values. To add `freqs` as an argument would require it along with (`fcen`,`df`,`nfreq`) to be keywords which is not what we want.

**Comment by stevengj** [comment]
Basically, @ChristopherHogan's suggestion boils down to adding something like this patch:
```diff
diff --git a/python/meep.i b/python/meep.i
index f4180caf..a5979c13 100644
--- a/python/meep.i
+++ b/python/meep.i
@@ -962,6 +962,8 @@ meep::volume_list *make_volume_list(const meep::volume &v, int c,
 // typemaps needed for add_dft_fields
 //--------------------------------------------------
 
+%apply (const double* IN_ARRAY1, size_t DIM1) {(const double* freqs, size_t Nfreq)}
+
 %typecheck(SWIG_TYPECHECK_POINTER) const volume where {
     int py_material = PyObject_IsInstance($input, py_volume_object());
     $1 = py_material;
diff --git a/src/dft.cpp b/src/dft.cpp
index 83be2ae8..3af24f35 100644
--- a/src/dft.cpp
+++ b/src/dft.cpp
@@ -165,7 +165,7 @@ dft_chunk *fields::add_dft(component c, const volume &where, double freq_min, do
                  use_centered_grid, vc);
 }
 
-dft_chunk *fields::add_dft(component c, const volume &where, const std::vector<double> freq,
+dft_chunk *fields::add_dft(component c, const volume &where, const double *freq, size_t Nfreq,
                            bool include_dV_and_interp_weights,
                            complex<double> stored_weight, dft_chunk *chunk_next,
                            bool sqrt_dV_and_interp_weights, complex<double> extra_weight,
@@ -184,7 +184,7 @@ dft_chunk *fields::add_dft(component c, const volume &where, const std::vector<d
   dft_chunk_data data;
   data.c = c;
   data.vc = vc;
-  for (size_t i = 0; i < freq.size(); ++i)
+  for (size_t i = 0; i < Nfreq; ++i)
     data.omega.push_back(2*pi*freq[i]);
   data.stored_weight = stored_weight;
   data.extra_weight = extra_weight;
diff --git a/src/meep.hpp b/src/meep.hpp
index 1f4444b1..75a5ecd5 100644
--- a/src/meep.hpp
+++ b/src/meep.hpp
@@ -1732,7 +1732,16 @@ public:
                      bool sqrt_dV_and_interp_weights = false,
                      std::complex<double> extra_weight = 1.0, bool use_centered_grid = true,
                      int vc = 0);
-  dft_chunk *add_dft(component c, const volume &where, const std::vector<double> freq_,
+  dft_chunk *add_dft(component c, const volume &where, const std::vector<double> freq,
+                     bool include_dV_and_interp_weights = true,
+                     std::complex<double> stored_weight = 1.0, dft_chunk *chunk_next = 0,
+                     bool sqrt_dV_and_interp_weights = false,
+                     std::complex<double> extra_weight = 1.0, bool use_centered_grid = true,
+                     int vc = 0) {
+    return add_dft(c, where, freq.data(), freq.size(), include_dV_and_interp_weights, stored_weight, chunk_next,
+                   sqrt_dV_and_interp_weights, extra_weight, use_centered_grid, vc);
+  }
+  dft_chunk *add_dft(component c, const volume &where, const double *freq, size_t Nfreq,
                      bool include_dV_and_interp_weights = true,
                      std::complex<double> stored_weight = 1.0, dft_chunk *chunk_next = 0,
                      bool sqrt_dV_and_interp_weights = false,
```
Similarly for *any* Python-callable method where we currently accept `std::complex<double> freqs` — you have to add a second lower-level method that takes `const double *freq, size_t Nfreq`

Then in the Python `DftObj` types (used for delayed initialization), where we currently store an `fcen, df, Nfreq` you will instead store a `freqs` array, mirroring what we do in C++.
