### ISSUE TITLE
near to far field transformation for cylindrical coordinates

### ISSUE THREAD

**Issue by oskooi** [NanoComp/meep#1086]
With the demonstration of launching planewaves in cylindrical coordinates (#1085), a useful additional capability would be to compute the focusing properties of a rotationally-symmetric, diffractive lens via a near-to-far field transformation.

This feature can be validated/demonstrated by comparison with analytic solutions using three possible tests/examples:

1. an [axicon](https://www.edmundoptics.com/knowledge-center/application-notes/optics/an-in-depth-look-at-axicons/)
2. a [Fresnel zone plate](https://en.wikipedia.org/wiki/Zone_plate) ([analytic solution](https://journals.aps.org/pre/abstract/10.1103/PhysRevE.49.5797))
3. a [circular aperture](https://www.tandfonline.com/doi/full/10.1080/09500340.2014.944236) (or [Poisson spot](https://en.wikipedia.org/wiki/Arago_spot))

(thanks to Prof. Rajesh Menon at the U. Utah for the suggestions.)

**Comment by stevengj** [comment]
This is certainly possible.  The difficulty is simply getting the Green's function that relates the solution at a point in the (r,z) plane to an arbitrary (x,y,z) point for the near-to-far calculation.

The simplest way is probably to use our existing `green3d` function and integrate it numerically over φ.   (For a periodic integral like this, you can just use equally spaced points and keep doubling the number of points until it converges to the desired tolerance, since equally spaced points converge exponentially fast for smooth periodic integrands.)   This is relatively expensive but should be easy to implement.

A more sophisticated approach would be to try and do the integral over φ analytically.   I vaguely recall that this is possible but leads to some nasty special function (a hypergeometric function?), but I'm not confident in my recollection here.  Even if we do this, however, we'll want the brute-force numeric-integration approach anyway in order to check it, so I would suggest implementing the numerical-integration approach first.

**Comment by oskooi** [comment]
To clarify the implementation strategy: this requires modifying `dft_near2far::farfield_lowlevel` such that every point in the DFT near fields object (below) is integrated over φ using the fixed angular dependence exp(imφ) by converting from cylindrical to 3d Cartesian coordinates and calling `green3d`? Any special tricks to improve convergence of the integral?

https://github.com/NanoComp/meep/blob/d068502332fef9b98e74d9f3cbf7ddec91d58558/src/near2far.cpp#L268-L285
