### ISSUE TITLE
offline computation of cost statistics

### ISSUE THREAD

**Issue by stevengj** [NanoComp/meep#1150]
Would be good to support "offline" computation of cost statistics for performance estimation (https://arxiv.org/abs/2003.04287): fragment statistics and chunk areas.  That is, compute them *without* allocating `structure` or `fields` objects, in a small (single-processor) calculation regardless of the number of processors that will eventually be used.

The fragment statistics code is already factored out of the fields and structure objects.     The main things to be done:

- [ ] Refactor [`structure::choose_chunkdivision`](https://github.com/NanoComp/meep/blob/6c10e745ab2e2e26627f82695c289fe5d79b6845/src/structure.cpp#L123-L226): have a new function that takes a `grid_volume` and a `symmetry` and a desired number of chunks (= number of desired processes) and returns a `std::vector<grid_volume>` of the divided chunks.  (Note that PML/boundary-layers do *not* need to be split into separate chunks here — that can still be done in `choose_chunkdivision`, since for performance modeling we only need to know the splitting *between* processes, not *within* a single process.)
- [ ] Add a higher-level interface in Python to compute and print out this data (e.g. from a `Simulation` object, *without* calling the `init_sim` method).

**Comment by stevengj** [comment]
One possible interface would be an environment variable, e.g. `MEEP_COSTESTIMATE_NPROC` — if this is set (to some integer `N`) then `init_sim` prints out the cost estimate for `MEEP_COSTESTIMATE_NPROC` processors and then exits.)

**Comment by oskooi** [comment]
Unfortunately, there is a complication when trying to compute the cost statistics without creating a `structure` object because `choose_chunkdivision` is a *private* function of the `structure` class:

https://github.com/NanoComp/meep/blob/29a92c0ab074259fcfa66b9d09e6c6254032ce46/src/meep.hpp#L798-L802

It is actually necessary to allocate the `structure` object since this enables subpixel smoothing (via `structure::set_materials`) which is used to count the number of anisotropic pixels in `fragment_stats::compute_stats()`:

https://github.com/NanoComp/meep/blob/29a92c0ab074259fcfa66b9d09e6c6254032ce46/src/meepgeom.cpp#L2002-L2015

Obviously, allocating the `structure` object (but not the `fields` object) consumes additional memory as part of `init_sim` but it seems that this is a small price to pay in order to keep the implementation of this feature straightforward.
