### ISSUE TITLE
Scale factor for adjoint source

### ISSUE THREAD

**Issue by yunxiangw** [NanoComp/meep#1209]
I know that the adjoint source is defined as the derivative of objective function with respect to the electric field. If the objective function is defined as the square of a (a is mode coefficient), then there should be a term da_dE in the adjoint source. But why does its value equal to the following equation? And why does we need to consider the fourier transform of the source's time profile?  

    da_dE = 0.5*(dV * self.cscale)
    scale = da_dE * dJ * 1j * 2 * np.pi * self.frequencies / np.array([self.time_src.fourier_transform(f) forf in self.frequencies])

**Comment by smartalecH** [comment]
>I know that the adjoint source is defined as the derivative of objective function with respect to the electric field.

Correct. We want to find ∂f/∂E

> If the objective function is defined as the square of a (a is mode coefficient)

Sounds good to me:
* f = |a|^2 = aā

>  then there should be a term da_dE in the adjoint source.

Yes, you are right (don't forget to use the CR calculus here...):
* ∂f/∂E = a * ∂ā/∂E + ā * ∂a/∂E but ā is independent of E so....
* ∂f/∂E = ā * ∂a/∂E

> But why does its value equal to the following equation?

First, let's agree that the mode coefficient, `a`, can be calculated from mode overlaps (`c1` and `c2`):
 * a = 0.5 * η * (c1 - c2) 

where η is the normalizing coefficient (more information in the [meep docs](https://meep.readthedocs.io/en/latest/Mode_Decomposition/#how-mode-decomposition-works)). So now we can differentiate with respect to the field (a complex quantity):
* ∂a/∂E = 0.5 * η

The scaling factor, η, is conveniently stored as `cscale` in the `get_eigenmode_coefficients()` routine.

Perhaps the real question is why `dV` is there? It's not actually from the  ∂a/∂E expression, but rather the derivation of the adjoint. It should really be on the next line for pedagogical reasons, but the math is obviously the same.

```python
da_dE = 0.5*(self.cscale)
scale = da_dE * dJ * 1j * 2 * np.pi * dV* self.frequencies / np.array([self.time_src.fourier_transform(f) forf in self.frequencies])
```
> And why does we need to consider the fourier transform of the source's time profile?

This question is a little trickier to answer. Remember we are setting the adjoint source with its amplitude while driving it with a Gaussian temporal envelope. We want to normalize out that extra Gaussian component at our center frequency so the adjoint fields at that frequency are correct. 

This gets really tricky for broadband adjoints, especially when multiple monitors are involved. Luckily we figured out a way to fit the correct time profile using radial basis functions.

**Comment by maweibest** [comment]
@smartalecH Thanks for guiding me to this issue and the detailed explanation. I searched other tutorials and some PhD thesis, but it seems to me that there is still a gap between theory and implementation, especially for a FDTD simulation. Your implementation with meep is definitely of great practical values to many newbees. 
Below are my concerns:
1. 
>First, let's agree that the mode coefficient, a, can be calculated from mode overlaps (c1 and c2):

    a = 0.5 * η * (c1 - c2)

where η is the normalizing coefficient (more information in the meep docs).
According to the meep mode coefficient tutorial [https://meep.readthedocs.io/en/latest/Mode_Decomposition/#how-mode-decomposition-works](url)
>Taking the inner product of both equations with the H and E fields of each eigenmode, we find
 ⟨**H_m|E_meep**⟩ = +(a_+m + a_−m) * v_m * A_S
 ⟨**E_m|H_meep**⟩ = -(a_+m - a_−m) * v_m * A_S

The forward mode coefficient a_+m = 0.5 * η * (c1 - c2), so η = v_m * A_S? 
Why for the derivative of mode coefficient with respect to electric filed ∂a/∂E, we simply have ∂a/∂E  = 0.5 * η? It seems to be related to both electric field and magnetic field in a complicated manner....

2.
> Perhaps the real question is why dV is there? It's not actually from the ∂a/∂E expression, but rather the derivation of the adjoint. It should really be on the next line for pedagogical reasons, but the math is obviously the same.

Can you elaborate more on this? According to Eq. 5.21 in Dr. Owen Miller's thesis, [http://optoelectronics.eecs.berkeley.edu/ThesisOwenMiller.pdf](url), it seems we should use volume itself not the reciprocal (dV = 1/self.sim.resolution is used in the code)? Or you have some other references I may look through to understand this.

3.
>This question is a little trickier to answer. Remember we are setting the adjoint source with its amplitude while driving it with a Gaussian temporal envelope. We want to normalize out that extra Gaussian component at our center frequency so the adjoint fields at that frequency are correct.

I understand that the Fourier Transform is used to normalize the amplitude of time-dependent Gaussian pulse at the frequency of interest, to match that of the default amplitude setting in meep source. Since FT is linear operation, we may simply divide our amplitude by the default gaussian amplitude in meep, like **required_amplitude / self.time_src.fourier_transform(f)**? 
But there are more terms in the normalization, **2 * np.pi, 1j, self. frequencies,**...
>scale = da_dE * dJ * 1j * 2 * np.pi * dV* self.frequencies / np.array([self.time_src.fourier_transform(f) forf in self.frequencies])

Where does all these terms comes from?

**Comment by smartalecH** [comment]
> It seems to be related to both electric field and magnetic field in a complicated manner...

Yes it's certainly related, but luckily not complicated. The rest of the derivative is simply a mode source with the same mode profile as the original monitor, but pointing in the opposite direction -- which is why we like using eigenmodes as objective arguments. This derivation focuses on the scaling of that mode source.

If we were to try and use a different quantity for our objective function, like the Poynting flux, then the rest of the derivative is a function of time and space that cannot be easily encapsulated like a mode profile is.

Owen talks about this in his thesis and in the [paper](https://millergroup.yale.edu/sites/default/files/files/LalauKeraly13.pdf) he and Chris wrote.

> it seems we should use volume itself not the reciprocal (dV = 1/self.sim.resolution is used in the code)?

Remember, `resolution` is pixels per unit length. So `1/resolution` is dx, and `1/resolution ** 3` is dV.

> Where does all these terms comes from?

- `da_dE` - derivative of the mode source with respect to the E field (just the scaling factor, since the rest of the derivative is encapsulated by another mode source)
- `dJ` - derivative of the objective function with respect to the mode coefficient
- `1j *2 *np.pi *self.frequencies`- definition of the adjoint in the frequency domain (this is just an omega term)
- `dV` approximation used in the definition of the adjoint to make all this magic work (review Owen's paper)

Use the chain rule to cascade where appropriate.

**Comment by yunxiangw** [comment]
@smartalecH Hi, I have two more questions about the adjoint source.

1. 
dV in the code is equal to ΔV in the Owen and Chris's paper, which represents a small enough volume perturbation. So in a 2D simulation dV=ds=(1/resolution) **2, in a 3D simulation dV=(1/resolution) **3. 
Is my understanding correct?

2. 

The second question is about this part:
>The rest of the derivative is simply a mode source with the same mode profile as the original monitor, but pointing in the opposite direction

We know that:
c1 = <Hm | E>
c2 = <Em | H>
∂a/∂E = 0.5 * η * ∂c1/∂E (Since c2 only contain H, ∂c2/∂E = 0 )
<a href="https://www.codecogs.com/eqnedit.php?latex=\dpi{100}&space;<H_m|E>=\int{(\vec{H_m^*}\times&space;\vec{E})\cdot&space;d\vec{s}}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\dpi{100}&space;<H_m|E>=\int{(\vec{H_m^*}\times&space;\vec{E})\cdot&space;d\vec{s}}" title="<H_m|E>=\int{(\vec{H_m^*}\times \vec{E})\cdot d\vec{s}}" /></a>
If we discrete the integral and calculate the partial derivative, we can get: 
<a href="https://www.codecogs.com/eqnedit.php?latex=\dpi{100}&space;\partial{c_2}/\partial{E}=ds(\vec{n}\times\vec{H_m^*})" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\dpi{100}&space;\partial{c_2}/\partial{E}=ds(\vec{n}\times\vec{H_m^*})" title="\partial{c_2}/\partial{E}=ds(\vec{n}\times\vec{H_m^*})" /></a>
In the 2D case, since the monitor is 1d, ds = dx = 1/resolution.
The adjoint source j is equal to **(1/resoluton)*(n x Hm\*)**, same as the equation (8) in the Owen and Chris's paper.
But if we use a eigenmode source as the adjoint source, j should be equal to **Em**. 
Why there is a difference between these two result?
