### ISSUE TITLE
Adjoint optimization: How to set the source using FDTD by meep?

### ISSUE THREAD

**Issue by maweibest** [NanoComp/meep#1226]
I am studying adjoint optimization for photonics, thanks for the supplementary adjoint module using meep and the great tutorial. One thing that confuses me is that most of the adjoint method are paired with frequency domain simulation, so that the set-up of adjoint sources, d_objective/d_E is straightforward (usually the objective is dependent on frequency). For FDTD simulation like meep, what is the correct way to setup the time-domain sources for adjoint simulation? 

I carefully read the source code about adjoint source setup and scaling below. 
https://github.com/NanoComp/meep/blob/65b69efa18e30a233896bb74c8f808e8f0a20b3a/python/adjoint/objective.py#L66-L85

Here are my confusions:
The adjoint field is stimulated by a scaled version of the eigen mode of the forward monitor, according to https://doi.org/10.1364/OE.21.021693, the mode overlap is an integration of the mode profile (Em, Hm) times the real field profile (E, H), so the derivative with respect to real field d_objective/d_E yields the scaled modal profile. **But how are these scaled factor calculated?** I noticed in the above code there are several components like da_dE, dV, self.cscale. I don't quite understand what are theses factors, and how are they calculated?  Any references on the specific case of mode overlap adjoint simulation?  Since I am not quite clear on the single frequency scaling case, your TODO also confuses me.
https://github.com/NanoComp/meep/blob/65b69efa18e30a233896bb74c8f808e8f0a20b3a/python/adjoint/objective.py#L87-L91

Hopefully anyone can explain this or provide some references.

**Comment by smartalecH** [comment]
> But how are these scaled factor calculated?

Check out #1209 for a "derivation" of the adjoint source term using eigenmode monitors/sources.

> your TODO also confuses me.

Yes my TODO also confuses me. As mentioned, the extra normalization shouldn't be required because we fit the time domain source profile to the desired frequency profile. There are some extra scale factors in meep's gaussian amplitude source that I need to more thoroughly work through (since it's a continuous-time gaussian, rather than discrete). This is a "brute-force" way to not worry about those.

Either way, it's not that big of a deal. Just some redundant calculations, which are completely negligible compared to timestepping. Luckily the gradient is still accurately calculated.

**Comment by smartalecH** [comment]
Can we close the issue?
