### ISSUE TITLE
graphene included in materials library

### ISSUE THREAD

**Issue by JohnWeiner** [NanoComp/meep#1230]
Graphene is of great interest to condensed matter theorists and experimentalists...especially those interested in light-matter interaction.  It would be nice to have the dispersive properties of graphene included in the materials library if possible.

**Comment by oskooi** [comment]
As explained in this [FAQ](https://meep.readthedocs.io/en/latest/FAQ/#how-do-i-model-graphene-or-other-2d-materials-with-single-atom-thickness), you would need the volume conductivity σ that is one pixel in thickness. Based on this, a simple approach is to just set this up as a narrow bandwidth simulation and use graphene's complex permittivity via the [`D_conductivity`](https://meep.readthedocs.io/en/latest/Materials/#conductivity-and-complex). This avoids having to fix the complex permittivity to a [Drude-Lorentzian susceptibility profile](https://meep.readthedocs.io/en/latest/Materials/#material-dispersion) which can be challenging.

**Comment by JohnWeiner** [comment]
I have incorporated a 2D σ conductivity, using a reference from Abajo (dx.doi.org/ph400147y|ACS Photonics 2014, 1, 135-152).  Using the interlayer separation for graphite of 0.3nm, it is possible to obtain a Drude-like expression for graphene permittivity and to incorporate it into the materials library.  I edited my local materials.py to do this, and the results are presented in the note that I am attaching to this comment.  However, I find that using this Drude-like permittivity expression yields reasonable looking results ONLY if I specify a thickness (say, object dimension in y direction) of 2/resolution in MEEP FDTD.  I had wanted to use 1/resolution to simulate a monolayer in the x-z plane, but when I specify 1/resolution, I only get nul amplitude fields (actually I haven't checked to see if the fields are strictly null or just very small).  I was wondering if this problem might simply be due to the YEE algorithm where E-field grid points and H-field grid points are intercalated in space (as well as in time).  Thus, I would need 2/resolution to get two grid planes: one for E-field grid points and one for H-field grid points.  I'm just a journeyman MEEP user and probably always will be so I would like to know your comments about how to get a true monolayer simulation...or even if it is possible.  The first part of the attached note is simply a note to myself so that I can remember where the eV_micron conversion factor comes from.  The second part has the graphene stuff.
[Notes on meep dispersion_v2.pdf](https://github.com/NanoComp/meep/files/4906760/Notes.on.meep.dispersion_v2.pdf)

**Comment by JohnWeiner** [comment]
Sorry...didn't mean to close this issue...at least not quite yet.

**Comment by JohnWeiner** [comment]
Sorry again...the 1/resolution vs 2/resolution problem has gone away.  Essentially the E- and H-fields are as expected even for the monolayer.  The seeming disappearance at 1/resolution was due to hot-spots in the PMLs. This must mean, however, that the FDTD compute code must somehow move the E and H grid points to the same plane.  If not, the field results, while reasonable looking might still be not correct.

**Comment by JohnWeiner** [comment]
[Notes on meep dispersion_v4.pdf](https://github.com/NanoComp/meep/files/5207683/Notes.on.meep.dispersion_v4.pdf)
Latest update to Notes (essentially to myself) of meep dispersion with respect to real metals and graphene.

**Comment by stevengj** [comment]
A more accurate approach is probably to do the equivalent of Meep's anisotropic subpixel averaging to smear out the plane into a continuously varying "tent-function" conductivity over a couple of pixels, but anisotropically — a different smearing for the in-plane conductivity vs. the out-of-plane conductivity.   (Of course graphene's conductivity is probably anisotropic to begin with, no?)

**Comment by oskooi** [comment]
@JohnWeiner, feel free to create a PR to add graphene to the materials library (in the form of a Drude conductivity based on your notes). Additionally, it would be helpful to include some documentation for this in [Materials](https://meep.readthedocs.io/en/latest/Materials/). A tutorial example would also be useful, if you have some suggestions.

**Comment by Nikolaos-MAtthaiakakis** [comment]
Hello, I thought that since a topic on graphene already exists I shouldn't start a new one. I have been trying to implement coordinate transform for simulations including a graphene layer. 

First I define graphene by
1) calculating the Drude model in the infrared region for graphene for the desired Ef 
2) setting the thickness of the layer as d=1/resultion =dz
3) Multiplying the conductivity with resolution sigma/dz (converted to SI units?)

Then in order to apply the coordinate transform in the z direction (transforming the thickness) I do the following
1) multiply the thickness by s
2) Define the Jacobian as J = (1 0 0; 0 1 0; 0 0 s)
3) use graphene.transform(J)
4) The air around the graphene region is also transformed accordingly

Of course this way the graphene thickness is no longer single pixel (something that could possibly happen by originally setting d=1/(resolution*s) since after the transform it will end up as single pixel).

Sadly I am not yet having great success with this and testing takes time due to the large simulation region and small structure required for graphene plasmonics. I will update this information once I get this to work, any advise would be very welcome.

**Comment by Nikolaos-MAtthaiakakis** [comment]
The coordinate stretch for d=1/(resolution*s) seems to work. The frequency and shape of the scattering peak due to the graphene plasmons that I obtain from meep are identical to the ones from the BEM code I use. Thus its safe to say coordinate transform works for 2D materials while keeping them at single pixel thickness after the transform. This works well even for a 20 times scaling factor.

I am curious though if graphene could actually be simulated using a block with only two dimensions instead of a block where the third dimension is single pixel. In this situation the graphene should be modeled using purely the surface conductivity instead of a volumetric model.
