### ISSUE TITLE
More accurate gradients

### ISSUE THREAD

**Issue by smartalecH** [NanoComp/meep#1270]
Currently, the adjoint solver interpolates the forward and adjoint fields at the center of each yee voxel and uses those values to calculate the gradient. Consequently, the gradient is less accurate. While the accuracy of the gradient converges with the resolution, there are some applications that benefit from lower resolution accuracy (especially since the gradient converges differently for certain problems).

An easy solution for simple problems that only care about one DFT component is to evaluate the DFT field points directly on the yee grid and multiply accordingly. If the FOM is even slightly more complicated, however, then this approach doesn't work since each component lies on a different grid point. There doesn't seem to be a straightforward way to evaluate λAₚx in this scenario.

Is there a way to either account for the interpolation in the gradient itself or to somehow combine the different DFT components into the gradient without interpolating at all?

**Comment by stevengj** [comment]
In principle, there is no problem with incorporating the interpolation into the gradient.  When you compute the adjoint current, just multiply by the transpose of the interpolation matrix (which is particularly simple: to interpolate from the Yee grid to the center of a voxel, you just equally weight the neighboring points).

**Comment by oskooi** [comment]
@smartalecH, it might be helpful to take a look at Fig. 4 of the [Meep paper](http://ab-initio.mit.edu/~oskooi/papers/Oskooi10.pdf).

**Comment by smartalecH** [comment]
> When you compute the adjoint current, just multiply by the transpose of the interpolation matrix

Yes, this seems straightforward when compensating for the objective function argument monitors (this is how we deal with the material grid after all).

But how do we deal with the interpolation in the *design regions*? It doesn't seem like you can relate that back to the adjoint source. The literature tends to solve this problem by using an alternative to the Yee grid (which we obviously don't want to do).

**Comment by stevengj** [comment]
For the design region, i.e. for dealing with adjoint E field, I think you need to work on the Yee grid for each field component.  For example, the derivative with respect to εₓₓ at a single point in the Eₓ Yee grid involves the product of the forward and adjoint Eₓ fields at that point.  Then there is an interpolation coefficient to relate that back to the design degrees of freedom.

Things are more complicated for off-diagonal entries.  In that case it is probably better to work with Dₓ and ε⁻¹, since that's what Meep deals with internally, but the interpolation is trickier.

**Comment by stevengj** [comment]
Note that there is another correction: if you are deriving the adjoint equations in FDFD, realize that FDTD differs *even in frequency* domain because the exact time derivative is replaced by a finite difference.   This causes factors of iω to be replace by the [formula on this line](https://github.com/NanoComp/meep/blob/fb58a86c2ca30b5752baa64e3d695cdb19288ed0/src/cw_fields.cpp#L202).
