### ISSUE TITLE
local mkdocs server fails to launch

### ISSUE THREAD

**Issue by oskooi** [NanoComp/meep#1278]
#1240 is causing the local mkdocs server (`mkdocs serve` from the source tree) to abort with the error:

```
$ mkdocs serve
INFO    -  Building documentation... 
ERROR   -  Config value: 'markdown_extensions'. Error: Failed loading extension 'md_in_html' from 'md_in_html', 'markdown.extensions.md_in_html' or 'mdx_md_in_html' 

Aborted with 1 Configuration Errors!
```
This was working fine prior to this commit:
```
$ mkdocs serve
INFO    -  Building documentation... 
WARNING -  Config value: 'pages'. Warning: The 'pages' configuration option has been deprecated and will be removed in a future release of MkDocs. Use 'nav' instead. 
INFO    -  Cleaning site directory 
[I 200705 14:48:18 server:292] Serving on http://127.0.0.1:8000
[I 200705 14:48:18 handlers:59] Start watching changes
[I 200705 14:48:18 handlers:61] Start detecting changes
[I 200705 14:48:24 handlers:132] Browser Connected: http://127.0.0.1:8000/
```
@RobinD42

**Comment by oskooi** [comment]
Separately, it seems that #1240 removed large portions of important supplemental text from `Python_User_Interface.md`. For example, the section on [Array Slices](https://meep.readthedocs.io/en/latest/Python_User_Interface/#array-slices) used to include a description of all the parameters of `get_array` and `get_dft_array` including `vol`, `component`, `arr`, etc. which are no  longer there. Additionally, a lot of the formatting is now inconsistent (e.g., function names such as `Simulation.add_near2far(...)` and other code does not appear in code blocks).

It might be better to revert `Python_User_Interface.md` to its pre #1240 state until we sort out these issues which might take a while.

**Comment by RobinD42** [comment]
`mkdocs serve` still works fine here. Have you tried updating the packages in the python environment used when running it? I added the `md_in_html` extension in `mkdocs.yaml` in order to be able to wrap some html around the md that was generated for the docstrings. I don't recall needing to add any additional packages to be able to get it.

The docs about the array method parameters have been moved to the docstrings for the methods themselves, with some links to them in the Array Slices section. For example: https://meep.readthedocs.io/en/latest/Python_User_Interface/#Simulation.get_array

**Comment by RobinD42** [comment]
For `Simulation.add_near2far` I added the first line to the docstring because the actual method def is `def add_near2far(self, *args, **kwargs):` and I didn't want the documented usage of `add_near2far(fcen, df, nfreq, freq, Near2FarRegions..., nperiods=1)` to be lost. Changing formatting there is just a simple matter of editing the docstring. Or the method itself can be edited to so there is more details in the parameters than just `*args, **kwargs`.

IIRC there are probably just a few (2 or 3) others that I handled the same way.

**Comment by RobinD42** [comment]
FTR, here are the packages/versions I installed in a new minimal Py3.7 venv that runs `mkdocs serve` without errors for me.

```
$  pip list
Package                    Version
-------------------------- -------
click                      7.1.2
importlib-metadata         1.7.0
Jinja2                     2.11.2
livereload                 2.6.2
Markdown                   3.2.2
MarkupSafe                 1.1.1
mkdocs                     0.17.5
mkdocs-material            5.4.0
mkdocs-material-extensions 1.0
pip                        20.1.1
Pygments                   2.6.1
pymdown-extensions         7.1
python-markdown-math       0.7
PyYAML                     5.3.1
setuptools                 41.2.0
six                        1.15.0
tornado                    4.5.3
zipp                       3.1.0
```

Also, letting it use the latest mkdocs package (instead of pinning it to 0.17.5 as mentioned in the README) works fine as well, although I think there was an issue with using Python2 with it, or one of its dependencies.

**Comment by oskooi** [comment]
The local mkdocs server can build the markdown pages from the latest Meep master branch with mkdocs 0.17.5 but it fails when using mkdocs 1.0.4 with the error reported earlier related to `md_in_html`. (The latest version of mkdocs currently available from the conda-forge channel is 1.1.2 which I have not tested.)

The following is a list of markdown-related packages from two different Conda environments for the working (which matches your configuration) and failing mkdocs server.

**working**
```
$ conda list
markdown                  3.2.2                      py_0    conda-forge
mkdocs                    0.17.5                     py_0    conda-forge
python-markdown-math      0.7                        py_0    conda-forge
tornado                   4.5.3           py38h516909a_1002    conda-forge
```

**failing**
```
$ conda list
markdown                  2.6.11                     py_0    conda-forge
mkdocs                    1.0.4                      py_0    conda-forge
python-markdown-math      0.6                        py_0    conda-forge
tornado                   5.1              py36h470a237_1    conda-forge
```

**Comment by RobinD42** [comment]
I think `markdown==3.2.2` is the key factor. That's what is providing `md_in_html`.

mkdocs 1.1.2 and up-to-date dependencies works for me (still on a stock python3 fetching from pypi).

**Comment by oskooi** [comment]
The mkdocs server works with the latest version of each of the dependencies.

```
$ conda list
markdown                  3.2.2                      py_0    conda-forge
mkdocs                    1.1.2                      py_0    conda-forge
python-markdown-math      0.7                        py_0    conda-forge
tornado                   6.0.4            py38h1e0a361_1    conda-forge
```

For some reason, #1240 was causing something to break in a previous environment:
```
$ conda list
markdown                  2.6.11                     py_0    conda-forge
mkdocs                    1.0.4                      py_0    conda-forge
python-markdown-math      0.6                        py_0    conda-forge
tornado                   5.1              py36h470a237_1    conda-forge
```

Anyways, we should probably update the [README](https://github.com/NanoComp/meep/blob/master/doc/README.md) to remove the `mkdocs==0.17.5` pinned version and to just use the latest mkdocs/markdown packages.
