### ISSUE TITLE
ensuring that user-specified cell dimensions are equivalent to the actual cell dimensions

### ISSUE THREAD

**Issue by oskooi** [NanoComp/meep#1291]
As originally reported in #1277 and #1287, simulations involving Bloch-periodic boundary conditions can undergo symmetry breaking due to small changes in the cell dimensions and thereby the Bloch periodicity as a result of discretization errors introduced by the choice of the resolution. The effect of this symmetry breaking is to introduce first-order errors.

This effect can be demonstrated using a 1d line source with a sinusoidal amplitude function in a 2d cell with periodic boundaries. The line source spans the entire length *L* of the cell in the *x* direction and is defined using a cosine profile: cos(k<sub>x</sub>x) where k<sub>x</sub> = 2πm/L and m is an integer. The wavevector k<sub>y</sub> of the propagating modes can be computed analytically: for a frequency of ω (in c=1 units), the propagating modes are the **real** solutions of sqrt(ω<sup>2</sup>n<sup>2</sup>-k<sub>x</sub><sup>2</sup>) where n is the refractive index of the propagating medium. (This is analogous to the [diffractions orders of a binary grating](Python_Tutorials/Mode_Decomposition.md#transmittance-spectra-for-planewave-at-normal-incidence).) PMLs surround the cell in the *y* direction in order to absorb the outgoing flux. In this example, L=1.5, ω=2π, and n=3.5 for a total of |m|=5 propagating modes. This can be verified by computing the total flux radiated by the source in the *+y* direction for the evanescent m=6 mode and checking that it is "zero" (i.e., close to [machine precision](https://en.wikipedia.org/wiki/Machine_epsilon)).

```py
￼import numpy as np
￼import meep as mp
￼
￼resolution = 50 # pixels/um
￼
￼sx = 1.5
￼sy = 6.0
￼cell_size = mp.Vector3(sx,sy)
￼
￼dpml = 1.0
￼pml_layers = [mp.PML(direction=mp.Y,
￼                     thickness=dpml)]
￼
￼fcen = 1.0
￼
￼def src_amp_func(m):
￼    def _src_amp_func(p):
￼        return np.cos(2*np.pi*m*(p.x+0.5*sx)/sx)
￼    return _src_amp_func
￼
￼sources = [mp.Source(mp.GaussianSource(fcen,fwidth=0.2*fcen),
￼                     component=mp.Ez,
￼                     center=mp.Vector3(0,-0.5*sy+dpml),
￼                     size=mp.Vector3(sx,0),
￼                     amp_func=src_amp_func(6))]
￼
￼sim = mp.Simulation(cell_size=cell_size,
￼                    resolution=resolution,
￼                    k_point=mp.Vector3(),
￼                    boundary_layers=pml_layers,
￼                    sources=sources,
￼                    default_material=mp.Medium(index=3.5))
￼
￼flux_mon = sim.add_flux(fcen, 0, 1,
￼                        mp.FluxRegion(center=mp.Vector3(0,0.5*sy-dpml),size=mp.Vector3(sx)))
￼
￼sim.run(until_after_sources=20)
￼
￼flux = mp.get_fluxes(flux_mon)
￼print("flux:, {}".format(flux[0]))
```

Plotting the radiated flux as a function of the resolution (using a semi-logarithmic scale) reveals an unexpected finding.

![bug2](https://user-images.githubusercontent.com/7152530/87694787-794c4800-c743-11ea-8842-97b8edac95dc.png)

The radiated flux of the evanescent mode varies by nearly twelve orders of magnitude when the resolution changes by just one! Also, the radiated flux is "zero" (the correct/expected result) only when the resolution is an even number. These large variations are due to the cell dimensions in the periodic *x* direction which are displayed in the simulation output:

```
￼Computational cell is 1.5 x 6 x 0 with resolution 50
￼flux:, 6.788984186414434e-16
￼...
￼Computational cell is 1.5098 x 6 x 0 with resolution 51
flux:, 0.0004094502264147733
￼...
￼Computational cell is 1.5 x 6 x 0 with resolution 52
￼flux:, 5.484924186312514e-16
￼...
￼Computational cell is 1.50943 x 6 x 0 with resolution 53
￼flux:, 0.00035958138720120446
￼...
￼Computational cell is 1.5 x 6 x 0 with resolution 54
￼flux:, 4.543947667089586e-16
￼...
￼Computational cell is 1.50909 x 6 x 0 with resolution 55
￼flux:, 0.00033641577621399885
```
In this particular example, an even grid resolution results in a cell size in the *x* direction of 1.5 but something slightly larger whenever the resolution is odd. When the cell size in *x* is exactly 1.5 (even resolutions), the source does not radiate and the flux is therefore ~10<sup>-16</sup> (i.e., [round-off errors](https://en.wikipedia.org/wiki/Round-off_error)). However, when the cell size in *x* is not exactly 1.5 (odd resolutions), the source *does* radiate a small but non-trivial amount (~10<sup>-4</sup>) which is only due to the different periodicity. (The same symmetry-breaking errors affect the propagating |m| <= 5 modes though they are less pronounced.)

Fixing this bug requires making sure that the user-specified cell dimensions are equivalent to the actual cell dimensions by slightly padding the resolution as necessary to obtain an even number of pixels.

**Comment by stevengj** [comment]
I'm guessing that the problem is in the `grid_volume` constructor, so the first step would be setting up a `grid_volume` from a given `volume` with various resolutions and checking that the sizes match.

**Comment by RobinD42** [comment]
As suspected there is some differences between otherwise equivalent `volume` and `grid_volume` instances for various values of cell size and resolution. What it boils down to is that the `num` member of `grid_volume` is an array of `ints` and the floating point values passed to `vol2d` and others are rounded up to the next whole number. If the cell sizes used are not whole numbers then that rounding ends up with dimension lengths and volumes that are off a bit for any resolution that does not have a `size * resolution` that is a whole number. For example, here are the details for one of my test runs. Notice that for xsize of 1.5 and a resolution of 50 the num[0] is 75 as expected, but in the next group with a resolution of 51 it gets rounded up from 76.5 to 77 and that the resulting gv volume is no longer 9.0, but in the following group with resolution of 52 it is back to 9.0:

```
flux: 6.788984185859263e-16
volume: min_corner:{0.000000,0.000000,0.000000}, max_corner:{1.500000,6.000000,0.000000},  volume.full_volume(): 9.0
grid_volume {
  dim:2D, a:50.000000, inva:0.020000, num:{75, 300, 0}
  x =-0.76 -  0.74 (  1.5) 	  y =   -3 -     3 (    6)
}
gv volume: 9.0

flux: 0.00040945022641477333
volume: min_corner:{0.000000,0.000000,0.000000}, max_corner:{1.500000,6.000000,0.000000},  volume.full_volume(): 9.0
grid_volume {
  dim:2D, a:51.000000, inva:0.019608, num:{77, 306, 0}
  x =-0.764706 - 0.745098 (1.5098) 	  y =   -3 -     3 (    6)
}
gv volume: 9.058823529411764

flux: 5.484924185958303e-16
volume: min_corner:{0.000000,0.000000,0.000000}, max_corner:{1.500000,6.000000,0.000000},  volume.full_volume(): 9.0
grid_volume {
  dim:2D, a:52.000000, inva:0.019231, num:{78, 312, 0}
  x =-0.75 -  0.75 (  1.5) 	  y =   -3 -     3 (    6)
}
gv volume: 9.0

flux: 0.0003595813872012048
volume: min_corner:{0.000000,0.000000,0.000000}, max_corner:{1.500000,6.000000,0.000000},  volume.full_volume(): 9.0
grid_volume {
  dim:2D, a:53.000000, inva:0.018868, num:{80, 318, 0}
  x =-0.754717 - 0.754717 (1.50943) 	  y =   -3 -     3 (    6)
}
gv volume: 9.056603773584907

flux: 4.543947667104036e-16
volume: min_corner:{0.000000,0.000000,0.000000}, max_corner:{1.500000,6.000000,0.000000},  volume.full_volume(): 9.0
grid_volume {
  dim:2D, a:54.000000, inva:0.018519, num:{81, 324, 0}
  x =-0.759259 - 0.740741 (  1.5) 	  y =   -3 -     3 (    6)
}
gv volume: 9.0
[[50, 6.788984185859263e-16], [51, 0.00040945022641477333], [52, 5.484924185958303e-16], [53, 0.0003595813872012048], [54, 4.543947667104036e-16]]
```

In addition to the graph in the OP above with `xsize=1.5`, where the values toggle between low and high for even/odd resolution values, it becomes a little more clear when `xsize=1.25` and the pattern of the cycle is four elements long:
![download1](https://user-images.githubusercontent.com/808502/89935251-bc74cc00-dbc6-11ea-928b-eb9768f6f619.png)

And for completeness, here is the same test with `xsize=2.0`, which avoids the rounding errors:
![download2](https://user-images.githubusercontent.com/808502/89935538-2beabb80-dbc7-11ea-8612-5ea451b4d25c.png)

I've put some time into digging deeper to see if that was the sole cause of the errors, but the deeper I got the more I bumped in to the limits of my current understanding of the guts of meep and how things are supposed to work there. So I'm not entirely clear yet if there is more than the rounding problem. I did try things like truncating the initial parameters instead of rounding up, but that has the same problem, except the error values were just a little too small rather than a little too big.

I expect that the reason `grid_volume` uses integers is because it " is a box of pixels" and a theoretical pixel can't be divided into fragments smaller than 1. That makes sense, but when the initial parameters are floating point there is the possibilities for issues like this. I currently see a couple possibilities:

* Use all floating point values inside `grid_volume` and round to integers for return values as needed.
* Go all floating point for internal and return values, leave it up to the caller to decide what to do with it.
* Enforce the size and resolution values passed in to the factory functions like `vol2d` to be whole numbers and raise a Python exception or warning if they are not. If the dimensions of the grid are supposed to be whole pixels then this makes sense to me.

**Comment by stevengj** [comment]
My inclination here would be to round the resolution.  i.e. if the user passes a resolution `a` and a cell size `s`, we change `a` to `around = s / round(size / a)`.    This is mostly transparent to the user — things will still converge with resolution (even if the user employs the original resolution for some post-processing calculations) — more transparent to the user than potentially breaking the symmetry by changing the cell size.

However, the downside of changing the resolution is that then we need to change the resolution *per dimension*.  Currently the code assumes everywhere that Δx = Δy = Δz, so this would be a lot of code to go through to change that.
