### ISSUE TITLE
flux fields of a circular shape in cartesian coordinates

### ISSUE THREAD

**Issue by slagwad** [NanoComp/meep#1334]
Hello, I have a simulation consisting of nested annular rings of different materials where the source and boundaries need to be in cartesian coordinates.  I see that the meep::volume does have a is_cylindrical parameter.  I don't see this set to True for the examples in cylindrical coordinates so the setting of dimensions CYLINDRICAL forces these the volumes to be in cylindrical coordinates.  My questions are 1) what happens when I set is_cylindrical to TRUE and 2) what is the best way to program non rectangular flux regions.  Thank you

**Comment by stevengj** [comment]
The `is_cylindrical` flag is used so that when Python Meep passes vectors to C++ Meep it stores the components as (r,φ,z) cylindrical-coordinate `vec` data structures rather than in the (x,y,z) slots.   Basically it is necessary in cylindrical-coordinate simulations so that vector parameters are interpreted as cylindrical coordinates.   Mostly this is handled internally; you should never need to use the `is_cylindrical` flag yourself.

I don't understand the context of your question.  Are you doing a cylindrical simulation?  Why can't you convert from Cartesian to cylindrical coordinates as needed?  What do you mean by "the source and boundaries need to be in cartesian coordinates"?

**Comment by slagwad** [comment]
Hi stevengj, thank you for the further details.  Here is a simplified portion of my script to help illustrate the simulation geo.  Hope you can help!

....
cell_size = mp.Vector3(sx,sy,0)
boundary_layers = [mp.PML(dpml, direction=mp.Y, side=mp.High)]
....
sources = [mp.Source(mp.ContinuousSource(fcen, fwidth=df,is_integrated=True),
                         component=mp.Ex,
                         center=mp.Vector3(0,0.5*sy-dpml,0),
                         size=mp.Vector3(sx,0,sz))]
.....
core_diameter = 10
film_diameter = core_diameter + 2
.....
geometry = []
geometry.append(mp.Ellipsoid(material=zno_m, size=mp.Vector3(film_diameter, film_diameter,mp.inf), center=mp.Vector3(-sx/2,sy/2,0) ))
geometry.append(mp.Ellipsoid(material=ni_m,   size=mp.Vector3(core_diameter, core_diameter,mp.inf), center=mp.Vector3(-sx/2,sy/2,0) ))

So the cell is rectangular and the source is a flat plane continuous one but I would like to determine the flux in the film which is an Ellipsoid (cylinder really).  I imagine there is an easy way to do this in meep but I have not been able to figure it out.
Thanks in advance for your help.

**Comment by stevengj** [comment]
> So the cell is rectangular

Why not use cylindrical coordinates?  That would be a lot faster.

There is no way to use a cylindrical flux plane in a Cartesian simulation, if that is what you want.   (Because of Poynting's theorem, however, the flux through a cylindrical surface is equal to the flux if you deform the surface to a box as long as you deform it through a homogeneous lossless medium.)

**Comment by slagwad** [comment]
Hi Steve, I agree that cylindrical coordinates would ideal for the geometry and establishing the flux plane portion but I still need straight line sources and cell walls and I could not figure out how to do that cleanly in cylindrical coordinates.  You are right about the Poynting's theorem through a cylinder vs box.  I will attempt to use a box .  Thx again for the help.

**Comment by stevengj** [comment]
> straight line sources

Whatever incident field or source you are trying to create, you can decompose it into a Fourier series in exp(imθ), do the simulations for each m, and then sum the results.

> cell walls 

Why do you need Cartesian cell walls?

**Comment by stevengj** [comment]
(Note that you could also compute the cylindrical Poynting flux "manually" in a Cartesian simulation:  Use the dft_fields feature to compute the Fourier-transformed fields at a set of points around the cylinder, compute the Poynting flux from these, and integrate it yourself.)
