### ISSUE TITLE
various bugs in adjoint solver

### ISSUE THREAD

**Issue by oskooi** [NanoComp/meep#1405]
The following four bugs were discovered using pylint.

1. `self.frequencies` and `self.monitor` should be initialized to `None`.

https://github.com/NanoComp/meep/blob/41548a3df131ce7fb5497cf8e59ecd34f48c9866/python/adjoint/objective.py#L26-L38

same for:

https://github.com/NanoComp/meep/blob/41548a3df131ce7fb5497cf8e59ecd34f48c9866/python/adjoint/objective.py#L113-L118

and:

https://github.com/NanoComp/meep/blob/41548a3df131ce7fb5497cf8e59ecd34f48c9866/python/adjoint/objective.py#L170-L176

2. `==` should be replaced with `=`:

https://github.com/NanoComp/meep/blob/41548a3df131ce7fb5497cf8e59ecd34f48c9866/python/adjoint/objective.py#L61

3. There are two `return` statements rather than one:

https://github.com/NanoComp/meep/blob/41548a3df131ce7fb5497cf8e59ecd34f48c9866/python/adjoint/filter_source.py#L56-L57

4. `eta` is not defined:

https://github.com/NanoComp/meep/blob/41548a3df131ce7fb5497cf8e59ecd34f48c9866/python/adjoint/filters.py#L607-L608

**Comment by smartalecH** [comment]
1. I don't think python always requires initialization of class members to `None`... we use all of those variables throughout the code and haven't seen any issues.

2. Yes this is a bug -- we haven't ever done tests with EM sources in the z-direction.

3. The rect function here is legacy and not used. We use a nuttall window for the basis function.

4. This along with several other filter bugs is fixed in #1398.

**Comment by oskooi** [comment]
Fixed by #1427, #1590, #1592, and #1593.
