### ISSUE TITLE
negative array indices in step_update_EDHB

### ISSUE THREAD

**Issue by jianguan210** [NanoComp/meep#1482]
When the test cases "convergence_cyl_waveguide" and "symmetry" were ran with ASan, it reports the heap-buffer-overflow meep/src/step_generic_stride1.cpp:539:29 and heap-buffer-overflow meep/src/step_generic_stride1.cpp:551:46

My study shows that the index values `i - s1` and `i - s2` will hit negative values in LOOP_OVER_VOL_OWNED. When I used if statements `(i >=s1)` and `(i >= s2)` to conditionally access the arrays, test was passed without warnings. 
Since this loop macro is used in many places, could you please take a look and find a generic solution to fix this issue?

**Comment by oskooi** [comment]
To provide some additional information, this issue is related to *negative* array indices in `step_update_EDHB` of `step_generic.cpp` which were traced to the following two sets of lines.

1. linear, 2x2 off-diagonal ε:

https://github.com/NanoComp/meep/blob/2dcfa9fcc226e07bf3d177ba8318c867a79567a9/src/step_generic.cpp#L536

In this case, `OFFDIAG` is a function macro defined as:

https://github.com/NanoComp/meep/blob/2dcfa9fcc226e07bf3d177ba8318c867a79567a9/src/step_generic.cpp#L376-L378

In this case, the problem is with the `g` array index `i - sx` which is equivalent to `i - s1`.

2. nonlinear, diagonal ε:

https://github.com/NanoComp/meep/blob/2dcfa9fcc226e07bf3d177ba8318c867a79567a9/src/step_generic.cpp#L547-L548

The similar problem here are the `g1` and `g2` array indices `i - s1` and `i - s2`, respectively.

As mentioned in the initial comment, the errors from the address sanitizer generated by the two C++ unit tests `tests/convergence_cyl_waveguide.cpp` and `tests/symmetry.cpp` can be removed simply by enforcing the rule that these lines are invoked only for non-negative indices, that is when `i > s1` and `i > s2`.

**Comment by stevengj** [comment]
Weird!  At first glance, the field components that we average for off-diagοnal ε
![image](https://user-images.githubusercontent.com/2913679/117087854-bc9d9480-ad1e-11eb-9b33-681ba62e7c9a.png)
should always be in the chunk volume if we are averaging to an "owned" point (via `LOOP_OVER_VOL_OWNED`):
![image](https://user-images.githubusercontent.com/2913679/117087894-d2ab5500-ad1e-11eb-9788-59c2c98839b6.png)

**Comment by stevengj** [comment]
It might be helpful to print out the coordinates of the problematic point, i.e. add something like
```cxx
if (i - s1 < 0) {
    ivec iloc = gv->iloc(fc, i);
   // print out iloc
}
```

**Comment by oskooi** [comment]
Looking into this further, it seems the error is not related to negative array indices which must therefore mean it is due to the array indices being exceeded in the other (i.e., positive) direction.

Some more clues: the failing subtest in `tests/symmetry.cpp` (which according to `git blame` was added many years ago) also involves *cylindrical* coordinates (similar to the other failing test in `tests/convergence_cyl_waveguide.cpp`):

https://github.com/NanoComp/meep/blob/f2bae0cbacbd41182bb6da87571e980e0276011c/tests/symmetry.cpp#L984-L985

The error is related to the `chi3` nonlinearities since removing it (lines 145 and 146) from this subtest caused the error to go away:

https://github.com/NanoComp/meep/blob/f2bae0cbacbd41182bb6da87571e980e0276011c/tests/symmetry.cpp#L140-L146

(The error is not related to the *z*-mirror symmetry.)

**Comment by oskooi** [comment]
The failing subtest in `tests/convergence_cyl_waveguide.cpp` involves subpixel smoothing `test_convergence_with_averaging` which produces *non-zero* off-diagonal elements for the ε tensor (whereas the no smoothing case `test_convergence_without_averaging` runs fine):

https://github.com/NanoComp/meep/blob/f2bae0cbacbd41182bb6da87571e980e0276011c/tests/convergence_cyl_waveguide.cpp#L175-L176

Following the suggestion of using an if-statement inside `step_generic_stride1.cpp` to print out the coordinates of the `ivec` at which the array index is negative reveals: `i = 0`, `s1 = 2` (i.e., `i - s1 < 0`)at the location (r,z) = (0,0).

Note that this particular test setup uses a Bloch-periodic boundary condition **k**=(k<sub>r</sub>,k<sub>z</sub>)=(0.1,0) in cylindrical coordinates. Removing this boundary condition did not affect the negative array index error.
