### ISSUE TITLE
segmentation fault in _default_material argument of create_structure_and_set_materials

### ISSUE THREAD

**Issue by jianguan210** [NanoComp/meep#1483]
When I ran a simulation case involved gradient calculation (`calculate_gradient()`), `default_material` in C++ implementation is never assigned the type of `material_type` and pointed to a valid memory allocation in the workflow of gradient calculation. So the conversion from `void*` to `material_type` is invalid. A simple workaround is to delete the "else if" branch, and It passed test cases. Please check this issue.

**Comment by stevengj** [comment]
> A simple workaround is to delete the "else if" branch

Which `else if` branch?

**Comment by stevengj** [comment]
I'm not clear on what simulation you are running — IIRC, anything that calls the routines in meepgeom.cpp should normally call `set_materials_from_geometry` first, which initializes `default_material`?

**Comment by oskooi** [comment]
To provide some additional information, the error reported by the address sanitizer is related to the line `mg = (material_data *)default_material;` which occurs at three places in `meepgeom.cpp`:

https://github.com/NanoComp/meep/blob/f2bae0cbacbd41182bb6da87571e980e0276011c/src/meepgeom.cpp#L402-L406

https://github.com/NanoComp/meep/blob/f2bae0cbacbd41182bb6da87571e980e0276011c/src/meepgeom.cpp#L444-L448

https://github.com/NanoComp/meep/blob/f2bae0cbacbd41182bb6da87571e980e0276011c/src/meepgeom.cpp#L2549-L2553

The issue here is that `default_material` is of type `void *` (defined by libctl) and in certain cases it is a NULL pointer (default value?) which cannot be cast into a `material_data *`. Perhaps we should just include a check for this case as part of the assignment?

**Comment by stevengj** [comment]
It seems like there is a missing `init_libctl` call in `_get_gradient`?  Also relevant to #1574.

**Comment by oskooi** [comment]
The problem here seems to be SWIG deleting the `_default_material` argument at the end of `create_structure_and_set_materials`. Inside this function, `_default_material` is passed to `init_libctl` which is then assigned to the global variable `default_material`:

https://github.com/NanoComp/meep/blob/ef8f6fc950fdf7c5feb34705afe375e40d12c795/python/meep.i#L1887-L1889

https://github.com/NanoComp/meep/blob/ef8f6fc950fdf7c5feb34705afe375e40d12c795/python/meep.i#L1907-L1908

https://github.com/NanoComp/meep/blob/ef8f6fc950fdf7c5feb34705afe375e40d12c795/src/meepgeom.cpp#L2060-L2070

Note that `_default_material` is of type `meep_geom::material_type` which is a pointer to the struct `material_data`:

https://github.com/NanoComp/meep/blob/ef8f6fc950fdf7c5feb34705afe375e40d12c795/src/material_data.hpp#L232

The SWIG generated file `meep-python.cxx` shows that the `_default_material` argument of `create_structure_and_set_materials` (`arg18`) is being deleted as part of the function `SWIGINTERN PyObject *_wrap_create_structure_and_set_materials(PyObject *SWIGUNUSEDPARM(self), PyObject *args)`:

```
    if (arg18) {
      if (arg18->medium.E_susceptibilities.items) {
        delete[] arg18->medium.E_susceptibilities.items;
      }
      if (arg18->medium.H_susceptibilities.items) {
	delete[] arg18->medium.H_susceptibilities.items;
      }
      delete[] arg18->weights;
      delete[] arg18->epsilon_data;
      delete arg18;
    }
```
The obvious solution seems to be to just prevent SWIG from deleting `_default_material`. Putting a `const` in front of this argument in the function header for `create_structure_and_set_materials `doesn't do this. Do we need to somehow explicitly tell SWIG not to delete `_default_material`?
