### ISSUE TITLE
unify split_by_effort and split_by_cost

### ISSUE THREAD

**Issue by stevengj** [NanoComp/meep#1498]
Steps:

1.  Change `split_by_cost` to not split by prime factors anymore — instead, like `split_by_effort`, always divide into two pieces along some axis, except that the "halves" are unequal (weighed by the number of processes that will go into each half) for an odd number of processes.  (Recursively.)  (Hence it will always give the requested number of chunks, regardless of the prime factorization.)

2. Give `split_by_cost` an option to use a simpler cost metric of just the number of pixels in a subvolume, similar to `split_by_effort`.

At this point, `split_by_effort` should be redundant (and slower) and can be eliminated.

**Comment by oskooi** [comment]
Just as a comparison, the chunk layouts for `split_by_effort` versus `split_by_cost` for a square 2d cell with just vacuum shows that they often produce different results:

![chunk_layout_2d](https://user-images.githubusercontent.com/7152530/107609888-0a5da180-6bf5-11eb-9381-ce69cda96dee.png)

The results for `split_by_effort` for the case of 5 and 10 chunks are clearly better than `split_by_cost` since those chunks have less surface area.

Also note that even when the results are similar (for the case of 8 chunks), the *ordering* of the chunks is different as demonstrated by their colors.
