### ISSUE TITLE
Additional phase factor in the adjoint simulation

### ISSUE THREAD

**Issue by mochen4** [NanoComp/meep#1507]
@mawc2019 first observed that when the source `width` parameter is changed in the adjoint tutorials (e.g. [https://github.com/NanoComp/meep/blob/master/python/examples/adjoint_optimization/01-Introduction.ipynb](url)), the adjoint gradient and finite difference gradient become inconsistent. It seems that the adjoint source is off by a phase factor, which comes from the source cutoff as pointed out by @stevengj later. Specifically, we propose to change 
https://github.com/NanoComp/meep/blob/c9cf31bc47adf1b47c0aea033b3f9a7f61628f65/python/adjoint/objective.py#L252

to

```python
width_phase = src.frequency * src.width * src.cutoff
adj_src_phase = np.exp(1j*np.angle(src_center_dtft)) * np.exp(-2j*np.pi*width_phase)
```
The above change seems to work for arbitrary source `width` and `cutoff` now. @smartalecH please check if you have similar results, and what is the best way to incorporate the change into the code.

**Comment by smartalecH** [comment]
Linking #1471.

I'm a little surprised that the existing `adj_src_phase` isn't working, as it's the actual DTFT (as meep performs it) of the time profile.

Do you know why this additional phase factor is needed? Normally I'm happy to see a bug fix, but it would be good to understand what's going on here first.

Now that I think about it, we should only need a scale factor, `adj_src_phase` for the single frequency case, not the broadband case, since the broadband case uses a custom fit time profile.

**Comment by stevengj** [comment]
It looks like on line 256 of objective.py it should be normalizing by the adjoint-source DFT instead of the [forward-source DTFT](https://github.com/NanoComp/meep/blob/c9cf31bc47adf1b47c0aea033b3f9a7f61628f65/python/adjoint/objective.py#L248), and it just happens to work because the forward and adjoint simulations use the same source (which we probably shouldn't rely on — just always use a gaussian).    It seems like the `adj_src_phase` term should be completely gone — otherwise we are dividing by it twice?
