### ISSUE TITLE
meepgeom function to evaluate ε on a given grid

### ISSUE THREAD

**Issue by stevengj** [NanoComp/meep#1509]
Would be nice to have a meepgeom function to evaluate a `Simulation`'s `geometry` on any user-specified grid (i.e. a given `meep::volume` and resolution), without subpixel averaging.   (We already have the routines to evaluate ε at any given point in space, so we just need to expose this as a vectorized API.)

This will be especially useful in conjunction with #1503, because it will allow you to evaluate the optimized "level set" (MG + projection) at any desired resolution.

**Comment by oskooi** [comment]
Rather than create a new function which returns an array of ε values corresponding to a user-specified `meep::volume` and resolution, it might be easier to just expose the existing function `geom_epsilon::chi1p1` in the Python interface:

https://github.com/NanoComp/meep/blob/a079d9bc13c92f4e70724fe88a50807549334e59/src/meepgeom.cpp#L743-L761

This way the user can call this function from Python for whatever grid points they desire and would be responsible for the bookkeeping.

Note that `geom_epsilon::chi1p1` calls [`geom_epsilon::get_material_pt`](https://github.com/NanoComp/meep/blob/a079d9bc13c92f4e70724fe88a50807549334e59/src/meepgeom.cpp#L692-L741) which for the case of a `MaterialGrid` in turns calls [`matgrid_val`](https://github.com/NanoComp/meep/blob/a079d9bc13c92f4e70724fe88a50807549334e59/src/meepgeom.cpp#L320-L369) where the interpolation+projection occurs *from the MaterialGrid*.

One complication with setting it up this way is that there is already a similar function `get_epsilon_point` in the [Python interface](https://meep.readthedocs.io/en/latest/Python_User_Interface/#field-computations) which returns ε at any given point by bilinearly interpolating from the nearest grid points:

https://github.com/NanoComp/meep/blob/a079d9bc13c92f4e70724fe88a50807549334e59/python/simulation.py#L2068-L2079

In particular, `get_epsilon_point` calls `fields::get_eps` which in turn calls `fields::get_chi1inv` where the interpolation occurs via [`grid_volume::interpolate`](https://github.com/NanoComp/meep/blob/a079d9bc13c92f4e70724fe88a50807549334e59/src/vec.cpp#L565-L619):

https://github.com/NanoComp/meep/blob/a079d9bc13c92f4e70724fe88a50807549334e59/src/monitor.cpp#L189-L198

The problem is that this function is *not* what we want because for the case of a `MaterialGrid` the ε grid points obtained in this function via `fields::get_chi1inv` have *already* been bilinearly interpolated + projected from the `MaterialGrid` during the `structure_chunks` initialization. This means that for the case of a projection with β >> 1, the values returned by `get_epsilon_point` would *not* be binarized (which is the expected result).

**Comment by stevengj** [comment]
The point is we want a new function in addition to `get_epsilon(...)` that "re-samples" the geometry *instead* of using the values on the Yee grid, with a user-specified resolution.

We'll want to add a function to meepgeom.cpp that does this: you pass a volume and a resolution (and/or a pre-allocated array), it will set up a geometry_tree for that volume, and loop over the points and call get_material_pt for each point and store it in the array.

**Comment by oskooi** [comment]
Here is one possible way to set this up using a new Python function `get_epsilon_grid` to be added to `python/simulation.py`:

```py
    def get_epsilon_grid(self, vol=None, res=0, grid_pts=None):
        """      
        Given a `Volume` `vol` and a resolution `res` or a NumPy array of grid points   
        `grid_pts` specifying the grid coordinates in $d$ dimensions as $d$ arrays stacked together 
        along a separate dimension $d$+1, compute $\\varepsilon$ for each grid point from the
        `geometry` rather than the Yee grid. This is useful for sampling to any arbitrary
        resolution the actual material grid that Meep uses internally to initialize the Yee grid.
        """
        if ((vol is not None) and (res != 0) and (grid_pts is None)):
            ds = 1/res
            if v.size.x != 0:
                x = np.arange(v.center.x-0.5*v.size.x,v.center.x+0.5*v.size.x,ds)
            else:
                x = v.center.x
            if v.size.y != 0:
                y = np.arange(v.center.y-0.5*v.size.y,v.center.y+0.5*v.size.y,ds)
            else:
                y = v.center.y
            if v.size.z != 0:
                z = np.arange(v.center.z-0.5*v.size.z,v.center.z+0.5*v.size.z,ds)
            else:
                z = v.center.z
            x_grid, y_grid, z_grid = np.meshgrid(x,y,z,indexing='ij')
            grid_pts = np.stack((x_grid,y_grid,z_grid),axis=3)
        elif ((vol is None) and (res == 0) and (grid_pts is not None)):
            ## 1d                             
            if (len(grid_pts.shape) == 1):
                x = 0
                y = 0
                z = grid_pts
                vol = mp.Volume(center=0.5*mp.Vector3(0,0,min(z)+max(z)),
                                size=mp.Vector3(0,0,max(z)-min(z)))
            ## 2d    
            elif (len(grid_pts.shape) == 3):
                x = grid_pts[:,:,0]
                y = grid_pts[:,:,1]
                z = 0
                vol = mp.Volume(center=0.5*mp.Vector3(min(x)+max(x),min(y)+max(y),0),
                                size=mp.Vector3(max(x)-min(x),max(y)-min(y),0))
            ## 3d        
            elif (len(grid_pts.shape) == 4):
                x = grid_pts[:,:,:,0]
                y = grid_pts[:,:,:,1]
                z = grid_pts[:,:,:,2]
                vol = mp.Volume(center=0.5*mp.Vector3(min(x)+max(x),min(y)+max(y),min(z)+max(z)),
                                size=mp.Vector3(max(x)-min(x),max(y)-min(y),max(z)-min(z)))
            else:
                raise RuntimeError("grid_pts has the wrong dimensions.")
            x_grid, y_grid, z_grid = np.meshgrid(x,y,z,indexing='ij')
            grid_pts = np.stack((x_grid,y_grid,z_grid),axis=3)

        ## call a C++ function to compute \epsilon via get_material_pt passing vol and grid_pts 
```

**Comment by stevengj** [comment]
I wouldn't call `meshgrid` — just pass 3 1d numpy arrays `x,y,z` (the ticks along each direction) to C++.  The only 3d array will be the array of the actual ε values.

**Comment by stevengj** [comment]
Note that the C++ should allocate the output ε array via `np.squeeze(np.empty((len(x), len(y), len(z)))` or similar.
