### ISSUE TITLE
support runtime choice of precision

### ISSUE THREAD

**Issue by stevengj** [NanoComp/meep#1549]
As commented in #1544, it would be good to be able to switch precision at runtime, by making `fields<T>`, `fields_chunk<T>`, `structure<T>`, and `structure_chunk<T>` template classes parameterized by the `realnum` type `T`.

**Comment by oskooi** [comment]
I have started working on this by first going through `meep.hpp` and templating any class which currently includes a `realnum` type or contains a member function which calls/uses a templated class. The problem is the sheer number of changes that are necessary. Apart from templating the classes `fields`, `fields_chunk`, `structure`, and `structure_chunk`, there are also other classes `susceptibility`, `boundary_region`, `flux_vol`, etc, that are also templated. Next I would need to template the definitions of all the member functions of these classes which are scattered across numerous files. This is not a straightforward task given the dependencies among the various classes/functions. It will take some time to set this up correctly.

A more practical alternative is to keep the current compile-time option and just enable single precision by default. All we would then need to do is modify the unit tests so that everything passes.

**Comment by oskooi** [comment]
Another complication to adding templates are two existing `typedef`s in `meep.hpp` which cannot be templated but which involve parameters that are templated classes `susceptibility` and `fields_chunk`:

https://github.com/NanoComp/meep/blob/2dcfa9fcc226e07bf3d177ba8318c867a79567a9/src/meep.hpp#L1318-L1323

https://github.com/NanoComp/meep/blob/2dcfa9fcc226e07bf3d177ba8318c867a79567a9/src/meep.hpp#L1476-L1479

**Comment by stevengj** [comment]
I think that any competent C++ programmer should be able to do this — it doesn't require any particular knowledge of how Meep works, and is just a (tedious but straightforward) matter of changing a type in one place and then tracing how that change  propagates through the library, which is a common software-engineering task.

**Comment by stevengj** [comment]
As an alternative, when you build with `--enable-single`, it could just rename the files when it installs from `meep` to `meep_single`.

**Comment by oskooi** [comment]
Replaced by #1544, #1563, #1688, etc.
