### ISSUE TITLE
Smoothing of curved boundaries in the geometry

### ISSUE THREAD

**Issue by nagmavohra** [NanoComp/meep#1556]
I have implemented a geometry using meep which has three regions of different materials with curved boundaries between these regions. I am using these commands in the code:

eps_averaging=True,
subpixel_maxeval=10000,
subpixel_tol=1e-4,

However, it gives the same results as with the eps_averaging=False was used. Am I missing anything in the code? I did not use the set_epsilon command. Do I need to use this command or any other command along with the above commands? Please advise so the smoothing of those curved boundaries can be achieved.

**Comment by stevengj** [comment]
How did you define the curved boundaries?  Using geometric objects, a material function, a material grid, …?

**Comment by nagmavohra** [comment]
I created a 2D binary mask in MatLab that contains three different regions. Then I imported this mask to meep, where I added few code lines to assign a different material to different binary values. See below the lines of the code as follows:

mat = sio.loadmat('DigitizedMask3.mat')     # load .mat file
Mask = mat['DigitizedMask3']

geometry=[]
for i in range(0,n1):
    for j in range(0,n2):
        if Mask[i,j]==1:
                geometry.append(mp.Block(mp.Vector3(), center =  mp.Vector3(),
                material=mp.Medium(epsilon=A1)))
        elif Mask[i,j]==2:
                geometry.append(mp.Block(mp.Vector3(), center =  mp.Vector3(),  
                material=mp.Medium(epsilon=A2)))
        else:
                geometry.append(mp.Block(mp.Vector3(), center =  mp.Vector3(),
                material=mp.Medium(epsilon=A3)))

**Comment by smartalecH** [comment]
Hmm it looks like you are just adding a bunch of block objects with constant permittivities. So subpixel smoothing is on by default. 

I don't see any "curved regions" though. Your binary mask is just a bunch of blocks -- if you want a curved surface then you need to parameterize it differently. 

There's not very much to go on from what you've posted. But eps_averaging=False *should* give you different results, provided your meep resolution is high enough to actually resolve the objects. 

Maybe try posting more of your code with the geometry output too (especially since we don't have your mat file) using plot2D().

**Comment by nagmavohra** [comment]
I thought to use a simpler geometry like cylinder embedded in a different medium instead of MATLAB mask until I figure out the sub-pixel smoothing issue. Please see below the part of the meep code. I used eps_averaging=True once and eps_averaging=False another time. please see the attached results of the top view of the cylinder. The discretization data of the geometry is as follows:

deltaT(ps):  0.023826006799868002 
deltaX(m):  1.4285714285714285e-05
 Number of cells:  154 ,  154 , 192
####################### Part of the code ####################
geometry = [mp.Block(mp.Vector3(0.001,0.001,0.0007), center = mp.Vector3(0,0,-3.25e-4), material=mp.Medium(index=1.36)),
                mp.Cylinder(center = mp.Vector3(0,0,-3.25e-4), radius = 3.5e-4, height = 0.0007, material=mp.Medium(index=1.67))]
 
    sim = mp.Simulation(resolution=resolution,
                            cell_size=cell_size,
                            boundary_layers=boundary_layers,
                            eps_averaging=True,
                            geometry=geometry,
                            sources=sources,
                            Courant=S)
###########################################################
![Cylinder geometry](https://user-images.githubusercontent.com/78975285/116788462-550ded80-aa6f-11eb-8c25-eb239daa2be2.png)

**Comment by smartalecH** [comment]
I'm not sure there is a subpixel smoothing issue. The way to check if subpixel smoothing is working is with a convergence plot, like in the meep paper and in the documentation. 

You won't be able to see a difference just by *looking* at the fields (usually) as the difference will be small. But you'll notice it as you ramp up the resolution and compare the accuracy with subpixel smoothing on and with it off. Subpixel smoothing will buy you second order accuracy. But it won't magically resolve small features. Your actual resolution needs to be able to do that first.

**Comment by stevengj** [comment]
You really don't want to import an image as a bunch of blocks in Meep, one per pixel!  I would use a material_grid object (which supports subpixel smoothing) or an epsilon_input_file instead

**Comment by nagmavohra** [comment]
Thank you for your comments!

**Comment by oskooi** [comment]
As @stevengj mentioned, to import a geometry as a bitmap image into Meep, you should use the [`MaterialGrid`](https://meep.readthedocs.io/en/latest/Python_User_Interface/#materialgrid) feature. The image as a `MaterialGrid` is then bilinearly interpolated onto Meep's Yee grid. To avoid discretization errors from resolving single image pixels, the resolution of the image should be at least twice the resolution of the Meep Yee grid (since the Yee grid is based on a staggered grid where the *E* and *H* fields are separated by a half Meep-pixel distance).
