### ISSUE TITLE
Use of incompatible licenses

### ISSUE THREAD

**Issue by ahoenselaar** [NanoComp/meep#1616]
The macros in the m4 folder are published under GPLv3. The rest of Meep is published under GPLv2.
These two licenses are not compatible.

**Comment by stevengj** [comment]
They are GPLv3 with the "autoconf exception":
```
#   As a special exception, the respective Autoconf Macro's copyright owner
#   gives unlimited permission to copy, distribute and modify the configure
#   scripts that are the output of Autoconf when processing the Macro. You
#   need not follow the terms of the GNU General Public License when using
#   or distributing such scripts, even though portions of the text of the
#   Macro appear in them. The GNU General Public License (GPL) does govern
#   all other use of the material that constitutes the Autoconf Macro.
```
which is designed to be compatible with any license, even proprietary software.

**Comment by stevengj** [comment]
See also: https://www.gnu.org/software/autoconf/manual/autoconf-2.69/html_node/Distributing.html

**Comment by ahoenselaar** [comment]
This seems to pertain to the output of an autoconf run. However, the M4 files themselves are part of the repository.

**Comment by stevengj** [comment]
> However, the M4 files themselves are part of the repository.

That's "mere aggregation" (which is discussed explicitly in the text of the GPL).  Just putting two files in the same repository doesn't make necessarily them derived works of one another.

**Comment by stevengj** [comment]
IANAL, obviously, but I think I'm relatively familiar (for a layperson) with the issues surrounding free/open-source licenses and what has been written about them by legal experts.  The case of autoconf, in particular, is not a new one — it's been around for decades, and the legal usage of autoconf in non-GPL projects is well established by now.

For example, the [Ogg Vorbis](https://github.com/xiph/vorbis) project is [publicly endorsed by the FSF](https://www.fsf.org/news/playogg.html), and is distributed under a BSD license rather than GPL (a choice [publicly endorsed by rms, the original GPL author](https://lwn.net/2001/0301/a/rms-ov-license.php3)), and Vorbis uses autoconf and distributes m4 files in its source repository.
