### ISSUE TITLE
subpixel smoothing gradients

### ISSUE THREAD

**Issue by smartalecH** [NanoComp/meep#1649]
Now that material grids have support for subpixel smoothing, it would be nice to enable gradient support.

Luckily, this should be rather straightforward given the current infrastructure. Since the [current recombination step ](https://github.com/NanoComp/meep/blob/76fab2b0aa0f65efb762e9944434997ab5c6d418/src/meepgeom.cpp#L2560)uses a finite difference to compute dA/dp, we just need to make sure that the finite difference routine also calls the new subpixel averaging routine (in this [function](https://github.com/NanoComp/meep/blob/76fab2b0aa0f65efb762e9944434997ab5c6d418/src/meepgeom.cpp#L2531)).

We also need to store the adjoint D fields, rather than the E fields.

**Comment by stevengj** [comment]
> We also need to store the adjoint D fields, rather than the E fields.

This might be an improvement, i.e. compute `-Eₐᵀ (∂ε⁻¹/∂p) D` instead of `Eₐᵀ (∂ε/∂p) E` as we are doing now.  The two should be equivalent in the continuum limit, but I have a feeling that the former is more accurate in the discrete case.  We'll have to look at it more closely, though, and it could be done separately from this issue.

**Comment by stevengj** [comment]
We could just return the `geom_epsilon` object and save it in the Python simulation object.

**Comment by stevengj** [comment]
(#1754 was only the refactoring part of this change, so it shouldn't have closed this issue.)
