### ISSUE TITLE
Adjoint solver with oblique planewave sources

### ISSUE THREAD

**Issue by mawc2019** [NanoComp/meep#1667]
Does the ``Near2FarFields`` adjoint solver support oblique planewave sources? I tried to launch an oblique planewave, but the finite-difference and adjoint gradients were inconsistent. The code is as follows, where the grazing angle is ``theta_in``.
When the planewave is obliquely incident with ``theta_in​`` taking, e.g., ``np.radians(60)``, the two types of gradients​ seem uncorrelated. Even if the planewave is normally incident with ``theta_in=np.radians(90)``, the two types of gradients are still inconsistent. But in this special case, they show a good linear relationship. At ``k=mp.Vector3()``, the two types of gradients become consistent.
The inconsistency also happens in ``FourierFields``.
```
import meep as mp
import meep.adjoint as mpa
import numpy as np
from autograd import numpy as npa
import math,cmath
Si = mp.Medium(index=3.4)
SiO2 = mp.Medium(index=1.44)

resolution,design_resolution = 20,20
Lx,Ly,pml_size = 4,4,1
cell_size = mp.Vector3(Lx,Ly+2*pml_size)
pml_layers = [mp.PML(pml_size, direction=mp.Y)]
design_width,design_height = 1,1

fcen,fwidth = 1/1.55,0.01/1.55
source_center,source_size  = mp.Vector3(0,-Ly/4),mp.Vector3(Lx,0)

theta_in = np.radians(60)
k = mp.Vector3(fcen*1.44).rotate(mp.Vector3(z=1), theta_in)

def pw_amp(k,x0):
  def _pw_amp(x):
    return cmath.exp(1j*2*math.pi*k.dot(x+x0))
  return _pw_amp

src = mp.GaussianSource(frequency=fcen,fwidth=fwidth)
source = [mp.Source(src,component=mp.Ez,center=source_center,size=source_size,amp_func=pw_amp(k,source_center))]

Nx,Ny = int(round(design_resolution*design_width)),int(round(design_resolution*design_height))

design_variables = mp.MaterialGrid(mp.Vector3(Nx,Ny),SiO2,Si,grid_type='U_MEAN')
design_region = mpa.DesignRegion(design_variables,volume=mp.Volume(center=mp.Vector3(), size=mp.Vector3(design_width, design_height)))

geometry = [mp.Block(center=design_region.center, size=design_region.size, material=design_variables)] # design region
sim = mp.Simulation(
    cell_size=cell_size,boundary_layers=pml_layers,k_point=k,geometry=geometry,
    sources=source,default_material=SiO2,resolution=resolution)

far_pt = [mp.Vector3(0,40,0)]
NearRegions = [mp.Near2FarRegion(center=mp.Vector3(0,Ly/4), size=mp.Vector3(Lx,0), weight=+1)]
FarFields = mpa.Near2FarFields(sim, NearRegions,far_pt)
ob_list = [FarFields]

def J(alpha):
    return npa.abs(alpha[0,0,2])**2

opt = mpa.OptimizationProblem(
    simulation = sim,objective_functions = J,objective_arguments = ob_list,
    design_regions = [design_region],fcen=fcen,df = 0,nf = 1,decay_by = 1e-5,decay_fields=[mp.Ez])

x0 = 0.5*np.ones(Nx*Ny)
opt.update_design([x0])
f0, g_adjoint = opt()

db,choose = 1e-4,5
np.random.seed(1905)

g_discrete, idx = opt.calculate_fd_gradient(num_gradients=choose,db=db)
g_discrete = np.array(g_discrete).flatten()

(m, b) = np.polyfit(np.squeeze(g_discrete), g_adjoint[idx], 1)
print("Randomly selected indices: ",idx)
print("Finite-difference gradient: ",g_discrete)
print("Adjoint gradient: ",g_adjoint[idx])
print("Slope: ",m)
print("Intercept: ",b)
```

**Comment by mochen4** [comment]
After a few tests, the issues seems to be about nonzero ``sim.k_point`` instead of sources being oblique. Apparently, inverting the sign of ``sim.k_point`` before the adjoint simulation (and changing it back afterwards) can solve the problem.

Specifically, I added ``self.sim.k_point *= -1`` right after [here](https://github.com/NanoComp/meep/blob/fdc4aa89a796bd7a4f7be013d7106bc587d61135/python/adjoint/optimization_problem.py#L289) and right before [here](https://github.com/NanoComp/meep/blob/fdc4aa89a796bd7a4f7be013d7106bc587d61135/python/adjoint/optimization_problem.py#L332), and the adjoint gradients become "consistent" with the finite difference gradients in the near2far cases. I only did a few preliminary tests (a few nonzero ``sim.k_point`` in the same setup above, but sources can be oblique or not oblique), and I haven't tested whether it works for the new FourierFields codes (https://github.com/mawc2019/meep/tree/fourier_adjoint) @mawc2019. I also suspect the issue may also occur for the current EigenmodeCoefficient, but I haven't tested it yet.

By "consistent", I mean the gradients are linearly correlated, but are off by a factor. It seems to be a factor of 1/2 in all of my preliminary test cases, i.e. ``g_discrete = 0.5*g_adjoint``. 

Intuitively, because it is the **adjoint**, it makes sense to invert the sign of ``sim.k_point``. At least for the near2far, it seems that no other work is needed. However, I am not sure where that factor of 1/2 may come from.

**Comment by stevengj** [comment]
Technically, I think we are transposing the Maxwell operator in the "adjoint" solve, but this is precisely why one needs to flip the sign of k.  The adjoint of the `(∇+ik)×` operator is `(∇+ik)×` (with appropriate boundary conditions), but the *transpose* is `(∇-ik)×`.   Equivalently, you can think of the adjoint problem as the "reciprocal" problem which sends everything "backwards", and to send a planewave backwards you need to flip the sign of k.

Maybe the 1/2 factor is a real vs. complex thing?   When you have a nonzero k point, the fields are complex so there are twice as many field components.   @smartalecH, did you test the adjoint solver with `force_complex=True`?

**Comment by mochen4** [comment]
Testing with the above setup and ``force_complex_fields = True`` in ``sim``, 1/2 factor appears even with zero k.

**Comment by stevengj** [comment]
Probably there should be a factor of 2 in `_adj_src_scale` (https://github.com/NanoComp/meep/blob/89c93498ead04290b42acbb35b2c09c9813e04eb/python/adjoint/objective.py#L53) when `self.sim.fields.is_real != 0`.   Should be an easy PR if you want to put it together — just change one of the adjoint tests to `force_complex_fields=True` (or loop over both values of this flag) to test it.

**Comment by stevengj** [comment]
In particular, it seems like this line should depend on whether we have the real or complex source:
https://github.com/NanoComp/meep/blob/89c93498ead04290b42acbb35b2c09c9813e04eb/python/adjoint/objective.py#L70-L71

**Comment by stevengj** [comment]
(Note: should be `self.sim.k_point *= -1 if self.sim.k_point` since `k_point` may be `None`.)
