### ISSUE TITLE
Missing factor of 2 in adjoint gradients for force_complex_fields=True

### ISSUE THREAD

**Issue by mochen4** [NanoComp/meep#1685]
When investigating https://github.com/NanoComp/meep/issues/1667, it occurred that adjoint gradients required an additional factor of 1/2 to match finite difference gradients. That factor probably came from the use of complex fields when ``sim.k_point`` is nonzero. When ``sim.k_point`` is zero, specifically setting ``force_complex_fields=True`` in simulations will also lead to the same factor of 1/2.

Preliminary tests have been performed with the same setup as in https://github.com/NanoComp/meep/issues/1667, but with multiple far points, multiple frequencies, etc. [Unit tests](https://github.com/NanoComp/meep/blob/master/python/tests/test_adjoint_solver.py) but with ``force_complex_fields=True`` are also examined. In all cases, the factor consistently appeared to be 1/2.

**Comment by stevengj** [comment]
@smartalecH, any ideas of why you'd be missing a factor of 2 in the complex case?

In the real-fields case we take the real parts of the adjoint currents, but nothing seems to explicitly take this into account in the code…

**Comment by smartalecH** [comment]
Nothing comes to mind immediately... I'd have to go through everything

**Comment by smartalecH** [comment]
Aha!

When we started this journey (many moons ago) we had a "magic 2" factor:

https://github.com/NanoComp/meep/blob/d662b0c4f518a4d14ad530394dd2d10d82887652/src/meepgeom.cpp#L2582-L2584

and 

https://github.com/NanoComp/meep/blob/d662b0c4f518a4d14ad530394dd2d10d82887652/src/meepgeom.cpp#L2615

that dates back to Homer's original adjoint code.

Now we know this is likely because meep takes the real part of a source, `s` such that our new source is `J = 0.5(s+s.conj())`.

In the complex case, of course, meep doesn't do this.

So the proper thing to do up would be eliminate the magic 2 in the above lines and introduce a check in the source placement code (all python) to see if the simulation is complex or not.
