### ISSUE TITLE
Complex ε typo + CW Medium class

### ISSUE THREAD

**Issue by smartalecH** [NanoComp/meep#1691]
In the[ meep documentation](https://meep.readthedocs.io/en/latest/Materials/#conductivity-and-complex), we say that a "constant" complex material can be defined around a small bandwidth using:
```python3
meep.Medium(epsilon=3.4, D_conductivity=2*math.pi*0.42*0.101/3.4)
```

Actually, we don't need the `2*pi` factor. Here's a simple test:

```
>>> import numpy as np
>>> import meep as mp
>>> from meep.materials import cSi
>>> fcen = 1/0.63
>>> a = cSi.epsilon(fcen)[0,0]
(15.128038844710053+0.12659924410469864j)
>>> temp = mp.Medium(epsilon=np.real(a), D_conductivity=2*np.pi*fcen*np.imag(a)/np.real(a))
>>> temp.epsilon(fcen)[0,0]
(15.128038844710053+0.7954465104586843j)
```

Clearly the results don't align. But if we omit the `2*pi`:

```
>>> temp = mp.Medium(epsilon=np.real(a), D_conductivity=fcen*np.imag(a)/np.real(a))
(15.128038844710053+0.1265992441046986j)
```
we get good agreement.

It might also be nice to have a class that inherits from `Medium` (e.g. `CWMedium`) that takes as an input the real/imaginary index and the center frequency. Then it performs the proper "fit" for the user (effectively eliminating any boilerplate).

**Comment by stevengj** [comment]
I think the bug is actually in the Python `_get_epsmu` function here, which omits the 2π factor: https://github.com/NanoComp/meep/blob/c8f9e8e103d03d8f5c7cfdce8918ecbd25790e0b/python/geom.py#L517-L520

I double-checked the C++ code and we never multiply by 2π when initializing the conductivity σ array, and the timestepping has a `dH/dt = ... -  σD` term, so indeed it corresponds to an imaginary part multiplied σ/ω = σ/2πf.

To do a rigorous verification of this, you can use the material-dispersion computation from the tutorial: https://meep.readthedocs.io/en/latest/Scheme_Tutorials/Material_Dispersion/#permittivity-function-of-an-artificial-dispersive-material

I agree that it would be nice to have a class (or probably just a constructor) that does this for you.  In particular, to have 2nd-order accuracy, you should probably use the "discrete iω" construction ala this line: https://github.com/NanoComp/meep/blob/9a6296574221bc44da46aee7b41b2321811ba8d3/python/adjoint/objective.py#L65-L66

**Comment by smartalecH** [comment]
> I think the bug is actually in the Python _get_epsmu function here, which omits the 2π factor:

Could be. Although I would assume that this test would fail if that were the case:

https://github.com/NanoComp/meep/blob/c8f9e8e103d03d8f5c7cfdce8918ecbd25790e0b/python/tests/test_medium_evaluations.py#L50-L55

**Comment by smartalecH** [comment]
>  In particular, to avoid a 2nd-order error, you should ideally use the "discrete iω" construction ala this line (although since the difference is 2nd-order in Δt it is not such a big deal)

I agree this would be nice, although this seems slightly problematic from an API perspective, as the geometry objects are initialized before the Δt is determined in the simulation object constructor. I guess we could allow the user to pass the resolution and Courant factor, but that seems a little overkill...
