### ISSUE TITLE
Proper `update_fields` interpolation scheme

### ISSUE THREAD

**Issue by smartalecH** [NanoComp/meep#1794]
The subpixel smoothing paper describes the update equation using the following figure:

![image](https://user-images.githubusercontent.com/24902086/137949379-4c5995bc-ee25-4174-bfec-040679eba558.png)

which is interpolation method 26(c) in the original [Werner and Cary paper](https://doi.org/10.1016/j.jcp.2007.05.008).

This method performs an interpolation, then the `chi1inv` multiplication, followed by another interpolation step. What's important is that this particular `chi1inv` component does *not* seem to be located on a typical grid point that it's originally stored (i.e. in the figure, the fields are interpolated to a "node" that doesn't store ε⁻¹ₓy).

The code, however, seems to just grab two ε points, one from a "leading corner" for each side that is being interpolated:

https://github.com/NanoComp/meep/blob/b6166b1b976eea03b9763505280f650f4aed20d1/src/step_generic.cpp#L381-L382

Note that `u[i]` aligns with `g[i]` and `u[i + s]` aligns with `u[i + s]`, leaving `g[i-sx]` and `g[i-isx+s]` "unbalanced". (Note that multiplying each point by it's corresponding `chi1inv` component is a different interpolation scheme altogether and not always stable).

These two operations don't seem to be the same to me, but maybe I'm missing something with how `chi1inv` is stored (I thought an entire row of the tensor was stored at each corresponding yee point).

**Comment by stevengj** [comment]
The index in the array doesn't correspond exactly to the location in space — for different field components, the same index corresponds to different spatial points, because different field components are stored on different Yee grids.    

For example, in the diagram above, all three of these spatial points correspond to the same array index `i` in their respective arrays:
![image](https://user-images.githubusercontent.com/2913679/138536522-07389943-74cc-45a0-aa0b-508362d1371c.png)
