### ISSUE TITLE
Error using load_flux with mpi

### ISSUE THREAD

**Issue by Nikolaos-MAtthaiakakis** [NanoComp/meep#1868]
Dear all,

I am facing an issue when trying to load data with `load_flux` on multiple cores. I either receive the following error 
```
meep: Aaack bad bug in split_at_fraction.
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0
```
or the code runs forever. On single core everything works fine. `if mp.am_master():` does not seem to help.

Thank you for your time and happy holidays and a happy new year to all.

Best wishes
Nikolaos

**Comment by oskooi** [comment]
Is it possible that you are running two parallel simulations whereby the flux is saved in the first run and then used in the second run (for normalization purposes) but the two runs are using a different number of processors? The [documentation](https://meep.readthedocs.io/en/latest/Python_User_Interface/) for `load_flux` states:
```
You must load from a file that was saved by save_flux in a simulation 
of the same dimensions (for both the cell and the flux regions) with the 
same number of processors.
```

**Comment by Nikolaos-MAtthaiakakis** [comment]
Thank you I will verify if it is because of a different number of cores used between reference and main simulation and will update this comment (only geometric difference is the inclusion of a metal cube).

I imagine if someone wanted to be able to run different number of processors between reference and main simulation they could save the reference flux with `get_flux` and `np.save` and then manually remove it from the flux in the main simulation?

**Comment by oskooi** [comment]
> I imagine if someone wanted to be able to run different number of processors between reference and main simulation they could save the reference flux with get_flux and np.save and then manually remove it from the flux in the main simulation?

`get_fluxes` (there is no  routine `get_flux`) will return the DFT fields as a list. If you want to save the DFT fields from a reference calculation in memory rather than writing it to disk before loading it in a second run, you should use `get_flux_data` at the end of the first run. You then use `load_flux_data` (or `load_minus_flux_data`) to load the data as part of the second run. Note that the same restrictions related to using an identical number of processes and cell size in the first and second runs applies to `load_flux_data` as `load_flux`. This restriction has to do with the way the DFT fields are stored internally in a parallel simulation (using "chunks") across the different processes and currently there is no workaround.

**Comment by Nikolaos-MAtthaiakakis** [comment]
Thank you, this is what I had previously done. I just wanted to have a code that doesn't need to run the reference every time.

For my error, it was reproducible by using 6 cores on both reference and main simulation. Maybe the way I wrote the code results in different chunks for the two runs. I will keep investigating.

By using  ,  and then `np.save` I could save the reference fluxes and then remove them from the main simulation flux manually after it was completed.

**Comment by Nikolaos-MAtthaiakakis** [comment]
The issue was that the second simulation had an extra monitor that caused the chunk division to be different. I included it in the reference simulation and now it works.
