### ISSUE TITLE
Fixed-angle broadband simulations

### ISSUE THREAD

**Issue by mountqi** [NanoComp/meep#1991]
**Lumerical FDTD Solutions** supports BFAST source, which enable broad band simulation with oblique incident wave.

[BFAST](https://support.lumerical.com/hc/en-us/articles/360034902273-Broadband-Fixed-Angle-Source-Technique-BFAST-)

Is there any similar implementation in meep?

**Comment by oskooi** [comment]
In Meep, a broadband planewave source at oblique incidence in a periodic structure generates planewaves at *different* angles. This is described in Section 4.5 "Efficient Frequency-Angle Coverage" of our book chapter https://arxiv.org/abs/1301.5366. As shown in Fig. 4.7, it is straightforward to compute the angle dependence of the output from e.g. the reflectance spectrum and then to perform additional simulations to generate results to span the entire angular parameter space.

The approach described in [IEEE Trans. Antennas & Propagation, vol. 62 , pp. 354-360 (2014)](https://ieeexplore.ieee.org/abstract/document/6651692) requires defining a new field and update equations which would be non-trivial to set up in Meep. Given its limitations (particularly the requirement that Δt be reduced to preserve numerical stability as well as limited applicability to dispersive materials, etc.), it does not seem to be of much practical use to justify the effort of supporting it.

**Comment by stevengj** [comment]
Yes, that paper makes the field update equations more expensive everywhere in space.

As an alternative, it occurred to me that it might be possible to implement frequency-dependent Bloch periodic boundary conditions to impose a frequency-independent angle.   In particular, for an angle θ, you really want Bloch-periodic boundary conditions

![image](https://user-images.githubusercontent.com/2913679/158073729-7b33ceac-af6a-45d8-a9df-3d81b01fe4fb.png)

for frequency-domain electric/magnetic field components û(x,ω), period *a*, and frequency-dependent Bloch phase kₓ = ωn/c sin(θ).  Let τ = ansin(θ)/c.   In the time-domain, this corresponds to a *delayed* boundary condition:

**u(a,t) = u(0, t –  τ)**

To implement this in the time domain, you would need to store τ/Δt = ansin(θ)/cΔt = ansin(θ)/SΔx timesteps worth of information, but only for the boundary points (where S is the Courant factor).  Since this is proportional to a/Δx, it require storage proportional to the whole computational cell, so it has similar *memory* scaling to the Liang paper (though the constant factor might be a better thanks to the sin(θ) factor) … but on the other hand the *computational* cost is much cheaper (because essentially there is no additional computational cost).

**Comment by stevengj** [comment]
One problem with the proposed scheme above is that we need to update boundary conditions in both directions.  e.g. we need to update u(a,t) from u(0, t – τ) but we also need to update v(0,t) from v(a, t + τ) for different field components u and v, which seems non-causal for at least one component?
