### ISSUE TITLE
unit test/tutorial for near2far+symmetry for antenna+ground

### ISSUE THREAD

**Issue by stevengj** [NanoComp/meep#2042]
A nice unit test might be to compute the far-field radiation pattern for an [antenna above a perfectly conducting ground](http://www.vias.org/radioanteng/radio_antenna_engineering_03_06_02.html).

Analytically, this can be computed by the method of images (it is the Green's function minus a mirror image).

Computationally, we'd do something similar, because the near2far transform in Meep only supports the homogeneous-medium Green's function, so it can't explicitly take into account the ground.  So, you'd model it as two antennas of opposite sign (odd mirror symmetric) surrounded by a single near2far box enclosing both sources.  Then impose an odd mirror symmetry in Meep so that it cuts the computational cell in half, effectively equivalent to a PEC boundary condition on one side.

Alternatively, you could have the near2far surface be an infinite plane above the dipole, but in that case you need #1952 or similar.

**Comment by oskooi** [comment]
Here are initial results of the radiation pattern of the antenna above the ground plane computed using the two different methods: (1) *one* antenna vs. (2) *two* antennas (method of images). The scripts used to generate these results are available in this [gist](https://gist.github.com/oskooi/f2456af1c611aa3b0421802eab8f7976). The agreement in the radiation pattern (heights/widths and positions of the lobes) is good for most of the angular range. However, there is a  noticeable discrepancy at ~0° (or equivalently ~180°) for the single-antenna case. This is due to the errors of the finite truncation of the computational cell and can simply be reduced by continuing to increase the cell size in the *x* direction.

The next step is to demonstrate that these results agree with the analytic theory.

**1 antenna**
![dipole_plot2D](https://user-images.githubusercontent.com/7152530/165017835-bc773fbe-0084-4d16-9c2d-f05c97f4b604.png)

![dipole_radiation_pattern_Lx240_Ly4_res50](https://user-images.githubusercontent.com/7152530/165018029-2efe20de-465d-4c93-b637-2ade4fd433c5.png)

**2 antennas**
![dipole_images_plot2D](https://user-images.githubusercontent.com/7152530/165017747-85eee3f3-1cb0-44ac-ba8e-8f20b06259fd.png)

![dipole_images_radiation_pattern_res50](https://user-images.githubusercontent.com/7152530/165018311-a324b0fd-e18e-4505-81b1-821da93d1e4f.png)

**Comment by GitHubaristos** [comment]
The far-field radiation pattern for a linear equi-spaced antenna array is the radiation pattern of a single antenna element placed at the center of the array (in this case the point between the antenna and its image) times the array factor AF = sin(Nu/2)/sin(u/2) [see e.g. Balanis, Chapter 6]. In this case, we have N=2 elements, so AF = 2cos(u/2). u = k*d*cosθ+β, where d and β are respectively the distance and excitation phase difference between consecutive elements, and θ the angle from the array center with respect to the axis through the elements. Ηere d/2=d' is the distance of the antenna from the ground plane and β=π for the image. Therefore, we get the final result AF = 2*sin(k*d'*cosθ).
So, in your case, you only need to calculate the radiation pattern for the E field of a single antenna and then multiply that with this AF for the effect of the ground plane.

**Comment by oskooi** [comment]
Thanks for this information. As shown in the following figure, the radiation pattern computed using the expression AF = 2sin(kd'*cosθ) does indeed seem to produce a radiation pattern which agrees with the Meep results. This is for the out-of-plane electric field polarization. The slight differences between the two methods are likely due to discretization errors in Meep which can be reduced simply by going to a larger resolution. 

For reference, this figure was generated using [these scripts](https://gist.github.com/oskooi/03a1915d1acfd8a31aeef52c44a86a97).

![pec_images_radiation_pattern_comparison_TE](https://user-images.githubusercontent.com/7152530/165756518-82ac91b4-85d5-4e1c-b832-a293c19d2a2e.png)
