### ISSUE TITLE
updated LED tutorial using reciprocity

### ISSUE THREAD

**Issue by stevengj** [NanoComp/meep#2080]
It would be nice to update the LED tutorial with an example using the [techniques described in our recent paper](https://arxiv.org/abs/2111.13046).  In particular, if you are just computing the power in the normal direction, then instead of a Monte-Carlo ensemble of sources you can get *exactly* the same result using a *single* reciprocal solve (or two in 3d, for 2 polarizations), analogous to Kirchhoff's law for thermal radiation.

**Comment by stevengj** [comment]
In particular, there are two steps:

1. Do the reciprocal solve v = A^{-\dagger} o_i where o_i is the output mode and A is the Maxwell operator.  This is just the reciprocal solve where you send and input mode in the opposite direction of your output mode.

2. Compute P = v* B v where B is the correlation matrix of your random currents.  If they are uncorrelated in space and consists only of electric currents (as in an LED), then B is a diagonal matrix that hits only the electric fields, so you get P = ∑ᵢ ∫ αᵢ(x) |Eᵢ(x)|² where αᵢ(x) is the mean-square amplitude of the the current in direction i and point x

**Comment by stevengj** [comment]
Note that approach is great for computing the power emitted in a single direction, or to compare that single-direction for two structures.   If you want to compute the light-extraction efficiency, where the denominator corresponds to emission in all directions, then the reciprocity trick is not useful.

To summarize, there are three cases:

1. Lots of emitters, but only a single output channel (or a small number).  Easy: use the reciprocity trick (section 2.3 of our paper).
2. Few emitters (e.g. one molecule), but lots of output channels.  Easy: use one solver per emitter (input channel), section 2.4 of our paper.
3. Lots of emitters, lots of output channels/directions.  Hard: need trace-estimation techniques (section 2.5 of our paper).

**Comment by oskooi** [comment]
Here is an initial attempt to set up the [LED emission calculation](https://meep.readthedocs.io/en/latest/Python_Tutorials/Custom_Source/#stochastic-dipole-emission-in-light-emitting-diodes) using reciprocity following the steps outlined [above](https://github.com/NanoComp/meep/issues/2080#issuecomment-1227697760). This example involves 10 dipole emitters which in the reciprocal calculation are replaced with 10 DFT point monitors. The reciprocal calculation is similar to the tutorial example involving two separate runs (textured and flat surface) and dividing the results to obtain a normalized quantity which is shown in the figure below. 

The results from the reciprocal calculation do not agree with the results from the tutorial (shown in the second figure below) although the order of magnitude is comparable. One cause of the discrepancy could be that I am using a mean-square amplitude of the current α=1 everywhere which may not be correct.

![led_flux_reciprocity](https://user-images.githubusercontent.com/7152530/189038861-e15c9ee6-c84a-48c4-9b1c-52cb9b42dedf.png)

![image](https://user-images.githubusercontent.com/7152530/189038906-93c90ae2-18f8-4348-a0f2-7addcd14d3ef.png)

![emitter_textured_plot2D](https://user-images.githubusercontent.com/7152530/189039044-5bef2324-39f9-4f1d-a41f-9084a5c5d8c9.png)

```py
import argparse

import numpy as np

import meep as mp
from meep.materials import Ag

import matplotlib
matplotlib.use('agg')
import matplotlib.pyplot as plt

parser = argparse.ArgumentParser()
parser.add_argument("-res", type=int, default=50, help="resolution (pixels/um)")
parser.add_argument("-nd", type=int, default=10, help="number of dipoles")
parser.add_argument("-nf", type=int, default=500, help="number of frequencies")
parser.add_argument(
    "-textured",
    action="store_true",
    default=False,
    help="flat (default) or textured surface",
)
args = parser.parse_args()

resolution = args.res

dpml = 1.0
dair = 1.0
hrod = 0.7
wrod = 0.5
dsub = 5.0
dAg = 0.5

sx = 1.1
sy = dpml + dair + hrod + dsub + dAg

cell_size = mp.Vector3(sx, sy)

pml_layers = [mp.PML(direction=mp.Y, thickness=dpml, side=mp.High)]

fcen = 1.0
df = 0.2
nfreq = args.nf
ndipole = args.nd
run_time = 2 * nfreq / df

geometry = [
    mp.Block(
	material=mp.Medium(index=3.45),
        center=mp.Vector3(0, 0.5 * sy - dpml - dair - hrod - 0.5 * dsub),
        size=mp.Vector3(mp.inf, dsub, mp.inf),
    ),
    mp.Block(
	material=Ag,
	center=mp.Vector3(0, -0.5 * sy + 0.5 * dAg),
	size=mp.Vector3(mp.inf, dAg, mp.inf),
    ),
]

if args.textured:
    geometry.append(
	mp.Block(
            material=mp.Medium(index=3.45),
            center=mp.Vector3(0, 0.5 * sy - dpml - dair - 0.5 * hrod),
            size=mp.Vector3(wrod, hrod, mp.inf),
	)
    )

# normally incident planewave                                                                                      
sources = [
    mp.Source(
        mp.GaussianSource(fcen, fwidth=df),
        component=mp.Ez,
        center=mp.Vector3(
            0, 0.5 * sy - dpml
        ),
        size=mp.Vector3(
            sx, 0
        ),
    )
]

sim = mp.Simulation(
    cell_size=cell_size,
    resolution=resolution,
    k_point=mp.Vector3(),
    boundary_layers=pml_layers,
    geometry=geometry,
    sources=sources,
)

dft_mons = []
for nd in range(ndipole):
    dft_mons.append(
        sim.add_dft_fields(
            [mp.Ez],
            fcen,
            df,
            nfreq,
            center=mp.Vector3(
                sx*(-0.5+nd/ndipole),-0.5*sy+dAg+0.5*dsub
            ),
            size=mp.Vector3()
        )
    )

sim.plot2D()
if mp.am_master():
    plt.savefig('emitter_plot2D.png',dpi=150,bbox_inches='tight')

sim.run(until=run_time)

freqs = mp.get_flux_freqs(dft_mons[0])

abs_flux = np.zeros(nfreq)
for nf in range(nfreq):
    dft_ez = np.zeros(ndipole,dtype=np.complex128)
    for nd in range(ndipole):
        dft_ez[nd] = sim.get_dft_array(dft_mons[nd], mp.Ez, nf)
    # compute the inner product for the correlation operator                                                       
    # by summing over all dipoles (α=1 everywhere)                                                 
    abs_flux[nf] = np.sum(np.abs(dft_ez))

if mp.am_master():
    surf_type = "textured" if args.textured else "flat"
    fname = f"flux_ndipole{ndipole}_nfreq{nfreq}_res{resolution}_{surf_type}.npz"
    with open(fname,'wb') as fl:
        np.savez(fl,freqs=freqs,abs_flux=abs_flux)
```

**Comment by stevengj** [comment]
> `np.sum(np.abs(dft_ez))`

You're missing the `**2` on the integrand.

**Comment by oskooi** [comment]
> You're missing the **2 on the integrand.

Unfortunately even with this change, the "backward" simulation results (i.e., planewave in air with point DFT monitors inside the LED) do not show good agreement with the "forward" simulation results (i.e., single dipole point sources inside the LED with Poynting flux measured in the air region above).

![led_fwd_vs_bwd_flux](https://user-images.githubusercontent.com/7152530/189539066-12d8da32-b243-4b97-aaeb-18e5c2ddace6.png)

**Comment by oskooi** [comment]
There seems to be a convergence issue with the reciprocal calculation in which the time-domain fields at the location of the DFT monitors do *not* decay away. This occurs because an incident planewave from air above the structure excites the Bloch modes of the patterned structure. These modes do not decay away and just bounce around indefinitely because the cell is periodic in the $x$ direction. In contrast, in the "forward" calculation involving point dipoles in the LED structure, we were measuring the Poynting flux in the *air region* which does converge with runtime.

Currently, we are using a lossless dielectric ($n$=3.45). Perhaps we need to switch to a lossy material for this demonstration?

**Comment by stevengj** [comment]
You can't couple into a guided mode (a lossless resonance) from an incident planewave — by definition of a guided/bound mode.

Furthermore, the same resonances that appear in the reciprocal "absorption" problem would also appear in the forward "emission" problem (via Purcell enhancement).   (It's possible that you truncated these accidentally in your forward calculation by running for too short a time there?)

Note that you are at k=0, so the only kind of true guided modes you would have are "BiC" (bound-in-continuum resonances), since they would have to occur above the light line.  Again, a BiC resonance by definition cannot couple to an incident planewave.   (On the other hand, slight symmetry breaking from e.g. discretization or even floating-point issues could cause BiC states to turn to very high-Q finite-lifetime resonances that you could slightly couple to.  Again, these would also affect emission.)    You could eliminate these by breaking the symmetry, e.g. by using a blazed grating.

**Comment by oskooi** [comment]
> It's possible that you truncated these accidentally in your forward calculation by running for too short a time there?

I verified that the results for the "forward" calculation are converged with runtime.

The closest I can get to reproducing the results from the forward calculation using a reciprocal setup is to use a Poynting flux line monitor *instead* of a collection of point DFT monitors. (This is possible because computing P = ∑ᵢ ∫ |Eᵢ(x)|² for a collection of point DFT monitors for the scalar $E_z$ field is proportional to the Poynting flux.) With this modification, the sharp resonant peaks in the normalized spectrum from the DFT fields monitors are gone but there is still a noticeable difference in the two sets of results. The Poynting flux results are also converged with runtime. 

The large difference indicates there is still a fundamental discrepancy between the forward and backward calculations that needs to be resolved.

![flux_line_nfreq501_res50_runtime16](https://user-images.githubusercontent.com/7152530/190956915-1e806f15-eac8-4ac2-99f7-c4d3c865750c.png)

![led_flux_line](https://user-images.githubusercontent.com/7152530/190957601-8c9c03e3-6de6-4b91-be66-eb94d472a890.png)

```py
    sim = mp.Simulation(
        cell_size=cell_size,
        resolution=resolution,
        k_point=mp.Vector3(),
        boundary_layers=pml_layers,
        geometry=geometry,
        sources=sources,
    )

    dft_flux = sim.add_flux(
        fcen,
        df,
        nfreq,
        mp.FluxRegion(center=mp.Vector3(0,-0.5*sy+dAg+0.5*dsub),
                      size=mp.Vector3(sx,0,0)),
        decimation_factor=0,
    )

    sim.run(until_after_sources=run_time)

    freqs = mp.get_flux_freqs(dft_flux)
    abs_flux = np.array(mp.get_fluxes(dft_flux))

    return freqs, abs_flux
```

**Comment by stevengj** [comment]
Measuring the Poynting flux is wrong, it should be integral of E^2

As discussed today, you are being inconsistent: your forward simulation is looking at the total Poynting flux, which includes contributions from *multiple* diffracted orders, whereas your reciprocal calculation is only computing the contribution from *normal* emission (the *zeroth* diffracted order).

The simplest way to make them consistent is it change your forward calculation to use an eigenmode monitor and only calculate the normal-emitted flux.   (Alternatively, you could change the reciprocal calculation to run several simulations, one per diffracted order, though then it is more expensive and you need to be more careful about normalization.)

**Comment by oskooi** [comment]
> The simplest way to make them consistent is it change your forward calculation to use an eigenmode monitor and only calculate the normal-emitted flux.

Modifying the forward calculation to compute only the normal-emitted flux using an eigenmode monitor does produce results which are in better agreement with the backward calculation. However, I can't seem to make the agreement nearly exact. The spectrum from the backward calculation contains sharp peaks which are not present in the forward calculation. 

I tried varying the resolution, number of point dipoles/DFT monitors, and runtime. The problem is likely the runtime which is somewhat tricky to choose consistently for the two cases because the fields never decay away to zero.

![forward_vs_backward_dipole10_nfreq501_res50](https://user-images.githubusercontent.com/7152530/192430696-4500c97f-f654-48ba-a44b-0ed1bd68e46b.png)

**Comment by stevengj** [comment]
Three things to try:

1. Try using a narrower-bandwidth source cetnered on e.g. f=1.03, to see if you can resolve those spectral features more clearly.
2. Try to move the reciprocal source (backward calc) and DFT flux monitor (forward calc) farther away, to try to make sure you're not accidentally coupling to evanescent fields
3. Break the mirror symmetry of the grating, e.g. use a "blazed" triangular grating or use two pillars side by side (one narrower and one wider).  This should get rid of symmetry-induced embedded eigenvalues (BiC states) at k=0 that you might be accidentally evanescently coupling into (though suggestion 2 should also help eliminate this).

**Comment by oskooi** [comment]
It seems that using a *slanted* grating (recommendation 3) produces results which are in better agreement though the agreement is still not exact. The other two recommendation did not change the results. I think this demonstrates that we now have a working example for a tutorial.

![forward_vs_backward_slanted_ndipole21_nfreq501_res50](https://user-images.githubusercontent.com/7152530/193415096-18ca99e2-8f4b-4a68-ab3b-18a80c64cb1e.png)

![slanted_led](https://user-images.githubusercontent.com/7152530/193415149-73b55fb9-0f18-4ffa-b6a0-0de804a016ae.png)

**Comment by oskooi** [comment]
Doubling the resolution to 200 from 100 improves the agreement which indicates that the results are simply not yet converged. The improved agreement at larger resolutions verifies that the forward and backward simulations are set up correctly and therefore produce equivalent results.

![forward_vs_backward_slanted_ndipole10_nfreq501_res100](https://user-images.githubusercontent.com/7152530/193464683-99eaa44c-2977-4959-8c41-dccd44a8c96a.png)

**Comment by stevengj** [comment]
Yes, the exact equivalence between the forward and reciprocal calculations (as defined above) is only at infinite resolution.

(There should also be a "discrete" version of the equivalence that is exact even at finite resolution, but you'd have to work it out based on the precise details of the Yee discretization etcetera.  Doesn't seem worth the trouble.)

**Comment by stevengj** [comment]
Which technique is converging faster?

**Comment by oskooi** [comment]
> Which technique is converging faster?

I was only able to compute the flux spectrum at resolutions of  50, 100, and 200. Based on this limited data, it's hard to tell from the convergence of the relative error in the L<sub>2</sub> norm of the flux of the forward and backward simulations which one is converging faster. We would need to go to larger resolutions to see the rate clearly. The problem though is that at a resolution of 200, the forward simulation takes nearly two days to complete.

![flux_convergence_fwd_vs_bwd](https://user-images.githubusercontent.com/7152530/193861390-f2d939de-8f66-46ca-8557-93179e490ca1.png)

**Comment by smartalecH** [comment]
Nice job getting this to work, @oskooi.

I noticed your `Simulation` object uses a zero k-point (`k_point=mp.Vector3()`) But you are trying to launch a planewave. Shouldn't your `Simulation` use the same k-point as the planewave (as discussed [here](https://meep.readthedocs.io/en/latest/Python_Tutorials/Eigenmode_Source/#planewaves-in-homogeneous-media))? How big of a difference do you see with and without it?

Also, I noticed that using an `Absorber` over a standard `PML`, as discussed [here](https://meep.readthedocs.io/en/latest/FAQ/#why-are-the-fields-not-being-absorbed-by-the-pml) works well when I try to simulate this. You mentioned you tried it and didn't see much of a difference (at a fixed resolution). Do you think it will help with convergence?

**Comment by oskooi** [comment]
> I noticed your Simulation object uses a zero k-point (k_point=mp.Vector3()) But you are trying to launch a planewave. Shouldn't your Simulation use the same k-point as the planewave (as discussed [here](https://meep.readthedocs.io/en/latest/Python_Tutorials/Eigenmode_Source/#planewaves-in-homogeneous-media))? How big of a difference do you see with and without it?

You are correct. A planewave propagating in air in the +y direction would have $\vec{k} = \omega(0,1,0)$ with $|\vec{k}|=\omega$. However, the 2d unit cell is periodic only in the $x$ direction. There are PMLs in the $y$ direction which means $k_y$ is actually irrelevant. We could have defined a non-zero `k_point` of the `Simulation` object but that would unnecessarily have involved complex fields which doubles the memory consumption and the number of floating-point operations during the time stepping. This is why I just used a `k_point` of zero. This should not affect the results since the boundary conditions in the $y$ are irrelevant assuming the PML is sufficiently thick to absorb all incoming waves.

> Also, I noticed that using an Absorber over a standard PML, as discussed [here](https://meep.readthedocs.io/en/latest/FAQ/#why-are-the-fields-not-being-absorbed-by-the-pml) works well when I try to simulate this. You mentioned you tried it and didn't see much of a difference (at a fixed resolution). Do you think it will help with convergence?

Replacing a PML with an `Absorber` can help if there are glancing-angle waves (e.g., due to diffracted orders of a grating) which are poorly absorbed by the PML. Since the fields did not seem to fully decay away in this example which I attributed to glancing-angle waves, I did try using an `Absorber` but in the end it did not affect the results.
