### ISSUE TITLE
document Jdata and Fdata of dft_ldos

### ISSUE THREAD

**Issue by stevengj** [NanoComp/meep#2148]
These fields are currently undocumented, but are potentially useful.

For example, if you want the total power exerted by a current source, I think it is just `real(Fdata)`.  (Whereas the LDOS is normalized by the Jdata.)   Maybe a tutorial on this would be good.

cc @mochen4

**Comment by oskooi** [comment]
In order to try to demonstrate that the total power radiated by a point-dipole emitter can be computed using the two different methods of (1) the Poynting flux over a closed box of DFT monitors enclosing the emitter or (2) the LDOS via `np.real(sim.dft_ldos_Fdata[0])`,  here is a simple test case with just vacuum and cylindrical coordinates involving an E<sub>r</sub> current at r=0 with m=-1 simulation.

Results from (2) are significantly larger than (1):  

```
radiated-power:, -38854.765174 (LDOS), 0.067620 (Poynting flux)
```

Equivalence cannot be demonstrated simply by flipping the sign of `np.real(sim.dft_ldos_Fdft[0])` and dividing by the `scale` factor of Δt/(2π) = 0.008 used to compute `Fdft`:

https://github.com/NanoComp/meep/blob/6aea4415f27af0ad51c9f34a6c452e327615be20/src/dft_ldos.cpp#L98-L101

https://github.com/NanoComp/meep/blob/6aea4415f27af0ad51c9f34a6c452e327615be20/src/dft_ldos.cpp#L151-L153

```py
import meep as mp
import numpy as np
import matplotlib
matplotlib.use('agg')
import matplotlib.pyplot as plt


resolution = 100.  # pixels/um                                                                                                                           

s = 8.
dpml = 1.
cell_size = mp.Vector3(s+dpml,0,s+2*dpml)

pml_layers = [mp.PML(dpml)]

fcen = 1.

sources = [mp.Source(
    src=mp.GaussianSource(fcen,fwidth=0.2*fcen),
    center=mp.Vector3(),
    component=mp.Er)]

sim = mp.Simulation(
    resolution=resolution,
    cell_size=cell_size,
    dimensions=mp.CYLINDRICAL,
    m=-1,
    sources=sources,
    boundary_layers=pml_layers)

flux_box = sim.add_flux(
    fcen,
    0,
    1,
    mp.FluxRegion(
        center=mp.Vector3(0.5*s,0,0.5*s),
        size=mp.Vector3(s,0,0)),
    mp.FluxRegion(
        center=mp.Vector3(s,0,0),
        size=mp.Vector3(0,0,s)),
    mp.FluxRegion(
        center=mp.Vector3(0.5*s,0,-0.5*s),
        size=mp.Vector3(s,0,0),
        weight=-1.0))

sim.run(mp.dft_ldos(fcen,0,1),
        until_after_sources=mp.stop_when_energy_decayed(
            5.,
            1e-7))

EJ = np.real(sim.ldos_Fdata[0])
flux = mp.get_fluxes(flux_box)[0]
print(f"radiated-power:, {EJ:.6f} (LDOS), {flux:.6f} (Poynting flux)")
print(f"other:, {sim.ldos_Fdata} (Fdata), {sim.ldos_Jdata} (Jdata)")

sim.plot2D()
if mp.am_master():
    plt.savefig('cyl_layout.png',dpi=150,bbox_inches='tight')
```

![cyl_layout](https://user-images.githubusercontent.com/7152530/180633190-893eed8d-1871-4d0e-98c6-a984bcd791df.png)

**Comment by stevengj** [comment]
In particular, currently I believe our `Fdata` is the sum of E(x) * conj(J(x)) where J is *just* the spatial amplitude dependence of the current, and `Jdata` is the Fourier transform of the *temporal* amplitude of the current.  

So I think what you want is `real(Fdata * conj(Jdata) * dV)` where `dV` is the volume element to convert the sum to an integral (e.g. 1/resolution^2 in 2d).

Cylindrical coordinates are more tricky however because of the r in the dV, which we currently don't take into account in `dft_ldos`, so I would recommend debugging this in 2d first.

**Comment by oskooi** [comment]
2D test case is working now using `-np.real(sim.ldos_Fdata[0]*np.conj(sim.ldos_Jdata[0]))*dA` where `dA = 1/(resolution**2)`. This result is equivalent to the Poynting flux.

Tested using E<sub>z</sub> and H<sub>z</sub> sources via the script below. The four data columns are `resolution`, `-np.real(sim.ldos_Fdata[0]*np.conj(sim.ldos_Jdata[0]))*dA`, Poynting flux, and ratio of third to second column (should be 1.0 in the ideal case).

**E<sub>z</sub> source**
```
flux:, 100, 9.827170, 9.823019, 0.999578
```

**H<sub>z</sub> source**
```
flux:, 100, 22.062042, 22.061681, 0.999984
```


```py
import argparse
import meep as mp
import numpy as np
import matplotlib
matplotlib.use('agg')
import matplotlib.pyplot as plt


parser = argparse.ArgumentParser()
parser.add_argument(
    '-res',
    type=float,
    help='resolution (pixels/μm)',
    default=100.,
)
args = parser.parse_args()

resolution = args.res  # pixels/um                                                                                                                           

s = 5.
dpml = 0.5
cell_size = mp.Vector3(s+2*dpml,s+2*dpml,0)

pml_layers = [mp.PML(dpml)]

n = 1.5 # refractive index of surrounding medium                                                                                                             

wvl = 1.0 # source wavelength                                                                                                                                
fcen = 1/wvl

src_cmpt = mp.Ez
sources = [mp.Source(src=mp.GaussianSource(fcen,fwidth=0.2*fcen),
                     center=mp.Vector3(),
                     component=src_cmpt)]

if src_cmpt == mp.Hz:
    symmetries = [mp.Mirror(mp.X,phase=-1),
                  mp.Mirror(mp.Y,phase=-1)]
elif src_cmpt == mp.Ez:
    symmetries = [mp.Mirror(mp.X),
                  mp.Mirror(mp.Y)]
else:
    symmetries = []

sim = mp.Simulation(cell_size=cell_size,
                    resolution=resolution,
                    sources=sources,
                    symmetries=symmetries,
                    boundary_layers=pml_layers,
                    default_material=mp.Medium(index=n))

flux_box = sim.add_flux(fcen,
                        0,
                        1,
                        mp.FluxRegion(center=mp.Vector3(0.5*s,0),
                                      size=mp.Vector3(0,s)),
                        mp.FluxRegion(center=mp.Vector3(-0.5*s,0),
                                      size=mp.Vector3(0,s),
                                      weight=-1.0),
                        mp.FluxRegion(center=mp.Vector3(0,0.5*s),
                                      size=mp.Vector3(s,0)),
                        mp.FluxRegion(center=mp.Vector3(0,-0.5*s),
                                      size=mp.Vector3(s,0),
                                      weight=-1.0))

sim.run(mp.dft_ldos(fcen,0,1),
        until_after_sources=mp.stop_when_fields_decayed(25,
                                                        src_cmpt,
                                                        mp.Vector3(),
                                                        1e-7))

sim.plot2D()
if mp.am_master():
    plt.savefig('ldos_2d.png',dpi=150,bbox_inches='tight')

flux = mp.get_fluxes(flux_box)[0]
dA = 1/(resolution**2)
ldos = -np.real(sim.ldos_Fdata[0]*np.conj(sim.ldos_Jdata[0]))*dA
ratio = flux/ldos

print(f"flux:, {int(resolution):d}, {ldos:.6f}, {flux:.6f}, {ratio:.6f}")
```

![ldos_2d](https://user-images.githubusercontent.com/7152530/181380605-6a50b197-0245-4691-8342-052218f4d809.png)

**Comment by stevengj** [comment]
In cylindrical coordinates, the tricky part is dV, which in principle contains a r factor (from r dr), but on the other hand a delta function in cylindrical coordinates should in principle have a 1/r factor that cancels this.

I don't remember exactly what we do here — when we set up the delta function amplitude [here](https://github.com/NanoComp/meep/blob/5cb0311fc9c41dff545be554167c21cd30e48531/src/sources.cpp#L456) we don't include a 1/r in the radial direction (maybe we should?), but maybe this correction is added elsewhere?  Note also that since you have an `Er` current, it is placed at Δr/2 in the Yee grid.

So I'm guessing that the dV factor in cylindrical coordinates for an `Er` source at the origin is either ΔrΔz (if we take care of the r factor somewhere I'm forgetting) or (Δr/2)ΔrΔz, i.e. either `1/resolution**2` or `0.5/resolution**3`.

**Comment by stevengj** [comment]
You commented today that the DFT flux is not converging with time, which would imply that some fields are not decaying away.  To get some idea of what is going on, it would be good to plot the fields after a long time to see what is left.

**Comment by oskooi** [comment]
Looks like the fields in vacuum in response to an E<sub>r</sub> source at $r=0$ which are not decaying away are those propagating in the $\textbf{z}$ direction. This can be [demonstrated](https://gist.github.com/oskooi/c5d2d9f0d2af342ed355abca8043c2eb?permalink_comment_id=4251314#gistcomment-4251314) by following @stevengj's suggestion and printing out the Poynting flux in each of the three monitors separately for various run times. 

The results shown below demonstrate that the fields propagating in the $r$ direction are fine because the Poynting flux in the $r$ direction is a constant value. However, the Poynting flux in the $z$ direction from each of the two monitors while equal in magnitude but opposite in sign varies with the run time.

The four data columns are: simulation time, flux (+z monitor), flux (+r monitor), flux (-z monitor).

```
150.0, -0.059667, 0.025234,  0.059667
250.0,  0.085347, 0.025234, -0.085347
450.0, -0.044804, 0.025234,  0.044804
```

Increasing the PML thickness in the $z$ direction changes the results but the trend is the same.

**Comment by oskooi** [comment]
I think I know what is going on here: there is a likely bug in the E<sub>r</sub> fields at $r=0$ and $z \neq 0$ (due to the PML?). If we shrink the size of the flux monitors in the $z$ direction to *exclude* $r=0$ then the flux is a constant value independent of the run time:
```py
flux_plus_z = sim.add_flux(
    fcen,
    0,
    1,
    mp.FluxRegion(
        center=mp.Vector3(0.5*s,0,0.5*s),
        size=mp.Vector3(0.95*s,0,0)))

flux_plus_r = sim.add_flux(
    fcen,
    0,
    1,
    mp.FluxRegion(
        center=mp.Vector3(s,0,0),
        size=mp.Vector3(0,0,s)))

flux_minus_z = sim.add_flux(
    fcen,
    0,
    1,
    mp.FluxRegion(
        center=mp.Vector3(0.5*s,0,-0.5*s),
        size=mp.Vector3(0.95*s,0,0)))
```
Four data columns are: simulation time, flux (+z monitor), flux (+r monitor), flux (-z monitor).
```
 150.0, +0.022526, +0.025275, -0.022526
 250.0, +0.022526, +0.025275, -0.022526
 450.0, +0.022526, +0.025275, -0.022526
```

These results suggest that the E<sub>r</sub> fields are propagating in the $z$ direction at $r=0$ and not decaying away due to absorption by the PML as they should be.

The cell layout shows the ±z flux monitors not extending to $r=0$.

![cyl_layout](https://user-images.githubusercontent.com/7152530/182050769-8214d9e9-4c39-4476-ac28-59c161c8ccf6.png)

(Based on this finding, it seems that using `dV = np.pi/(resolution**3)` to compute the total emitted power based on the LDOS via `-np.real(sim.ldos_Fdata[0]*np.conj(sim.ldos_Jdata[0]))*dV` matches the Poynting flux value.)
