### ISSUE TITLE
FourierFields adjoint returns 9 source objects

### ISSUE THREAD

**Issue by Alex-Kaylor** [NanoComp/meep#2238]
Why does the FourierFields objective's place_adjoint_source function return nine different meep.source.IndexedSource objects in 3D simulations (using a 2D or 3D monitor)? Are all of them necessary?

It seems like one source should be enough.

The objective returns nine sources regardless of monitor size, monitor shape, or tracked component. Multiple frequencies gives nine different sources per frequency. This does not occur in 2D (it returns a single source as expected).

The following code reproduces the issue:

```
import meep as mp
import numpy as np
import meep.adjoint as mpa

resolution = 4
silicon = mp.Medium(epsilon=12)

sxy = 6.0
sz = 4
cell_size = mp.Vector3(sxy,sxy,sz)
#mp.integrate_field_function()

dpml = 1.0
pml_xy = [mp.PML(thickness=dpml)]
pml_x = [mp.PML(thickness=dpml,direction=mp.X)]

eig_parity = mp.EVEN_Y+mp.ODD_Z
wg_height = 0.5
design_region_size = mp.Vector3(1.5,1.0,wg_height)
design_region_resolution = int(2*resolution)
Nx = int(design_region_size.x*design_region_resolution)
Ny = int(design_region_size.y*design_region_resolution)

# ensure reproducible results
rng = np.random.RandomState(9861548)

# random design region
#p = 0.5*rng.rand(Nx*Ny)
p = np.ones(Nx*Ny)

# random perturbation for design region
deps = 1e-5
dp = deps*rng.rand(Nx*Ny)

w = 1.0
wg_height = 0.5
waveguide_geometry = [mp.Block(material=silicon,
                                    center=mp.Vector3(),
                                    size=mp.Vector3(mp.inf,w,wg_height))]

fcen = 1/1.55
df = 0.2*fcen
mode_source = [mp.EigenModeSource(src=mp.GaussianSource(fcen,fwidth=df),
                                        center=mp.Vector3(-0.5*sxy+dpml,0),
                                        size=mp.Vector3(0,sxy-2*dpml,sz-2*dpml),)]
                                        #eig_parity=eig_parity)]

k_point = mp.Vector3(0.23,-0.38)


matgrid = mp.MaterialGrid(mp.Vector3(Nx,Ny),
                                mp.air,
                                silicon,
                                weights=np.ones((Nx,Ny)))

matgrid_region = mpa.DesignRegion(matgrid,
                                    volume=mp.Volume(center=mp.Vector3(),
                                                    size=mp.Vector3(design_region_size.x,
                                                                    design_region_size.y,
                                                                    design_region_size.z)))

matgrid_geometry = [mp.Block(center=matgrid_region.center,
                                size=matgrid_region.size,
                                material=matgrid)]

geometry = waveguide_geometry + matgrid_geometry

sim = mp.Simulation(resolution=resolution,
                    cell_size=cell_size,
                    eps_averaging = False,
                    boundary_layers=pml_xy,
                    sources=mode_source,
                    geometry=geometry,
                    force_complex_fields = True)


volume = mp.Volume(center=mp.Vector3(1.25), size=mp.Vector3(0,sxy-2*dpml,sz-2*dpml))
interesting_components = [mp.Hz,mp.Hy,mp.Ez,mp.Ey]

obj = mpa.FourierFields(sim, volume, mp.Ez)

mon = obj.register_monitors([1/1.55])
sim.run(until_after_sources=mp.stop_when_fields_decayed(100,mp.Ez,mp.Vector3(1.25,0),1e-4))

mon_size = sim.fields.dft_monitor_size(
            obj._monitor.swigobj, obj.volume.swigobj, mp.Ez
        )

dj_test = np.ones(mon_size)
sources = obj.place_adjoint_source(dj_test)
print(np.asarray(sources).size)

```

@mochen4 or @mawc2019 might be able to help.

I expect it's because of this line in the FourierFields objective:

```
        self.all_fouriersrcdata = self._monitor.swigobj.fourier_sourcedata(
            self.volume.swigobj, self.component, self.sim.fields, dJ
        )
```

Because we iterate over all components of _fouriersrcdata in the next line.

**Comment by mawc2019** [comment]
> The objective returns nine sources regardless of monitor size, monitor shape, or tracked component.

It depends. For example, if `size=mp.Vector3(0,sxy-2*dpml,sz-2*dpml)` in `volume` is replaced with `size=mp.Vector3(sxy-2*dpml,sz-2*dpml)` or `size=mp.Vector3(sxy-2*dpml,sz-2*dpml,0)`, the number of sources returned by the code is 2.

> I expect it's because of this line in the FourierFields objective:

Probably. The situation is similar in the `Near2FarFields` adjoint solver, which uses a [similar function](https://github.com/NanoComp/meep/blob/master/python/adjoint/objective.py#L387-L389). After I adapted the example code to `Near2FarFields`, 36 sources are returned.

> Why does the FourierFields objective's place_adjoint_source function return nine different meep.source.IndexedSource objects in 3D simulations (using a 2D or 3D monitor)?

I guess this issue is related to the [partition of chunks](https://github.com/NanoComp/meep/blob/master/src/dft.cpp#L1483) related to the allocation of sources. Likewise, `Near2FarFields` also undergoes a [similar process](https://github.com/NanoComp/meep/blob/master/src/near2far.cpp#L655).

> Are all of them necessary?

I think it depends on whether any of them are empty. Any thoughts on this and other questions, @mochen4 ?

**Comment by mochen4** [comment]
> I expect it's because of this line in the FourierFields objective:
> 
> ```
>         self.all_fouriersrcdata = self._monitor.swigobj.fourier_sourcedata(
>             self.volume.swigobj, self.component, self.sim.fields, dJ
>         )
> ```
> 
> Because we iterate over all components of _fouriersrcdata in the next line.

You only specify one component here ``obj = mpa.FourierFields(sim, volume, mp.Ez)``, and that is the only component. There is no iteration over components in ``FourierFields``; one must define individual object for each component. (On the other hand, we could rewrite the python function so that it takes a list of components instead. That should just be an extra loop over requested components, and could simplify the usage. Or we could do it in the C++ code.)

> I guess this issue is related to the [partition of chunks](https://github.com/NanoComp/meep/blob/master/src/dft.cpp#L1483)

That's right. One ``IndexedSource`` (when ``num_freq==1``) for each ``fourier_data``of the ``all_fouriersrcdata``
https://github.com/NanoComp/meep/blob/0a5aaeea16eeaea50ebeaaee5be8bf34a806adc0/python/adjoint/objective.py#L320

And there is one ``fourier_data`` for each ``dft_chunk``, from here:
https://github.com/NanoComp/meep/blob/0a5aaeea16eeaea50ebeaaee5be8bf34a806adc0/src/dft.cpp#L1481-L1555

``temp`` is ``all_fouriersrcdata``, and ``temp_struct`` is a single `fourier_data``. The takeaway of this block of code is that

```
initialize temp;
loop over dft_chunk{
initialize temp_struct;
...some computation...
add temp_struct to temp;
}
```

And the number of sources should be dependent on the monitor size.
> Are all of them necessary?

Generally yes, I believe. If the spatial dependency of adjoint sources is across several chunks, then we have to create separate sources. (Even if you have one large source, I think it would still be divided into chunks internally.)

Meanwhile, I don't see why the issue matters. You are working on Poynting flux, right? In python, you can just create FourierFields objects for relevant components, express the Poynting flux in the objective function, and the rest will be taken care of. The only issue is that the sizes of fields arrays may be different for different components (since they are on Yee grid), so you might need some interpolation in the objective function.

**Comment by Alex-Kaylor** [comment]
Thank you for both of your detailed comments! I didn't consider chunking, sorry if my question is a bit inane. 

>For example, if size=mp.Vector3(0,sxy-2*dpml,sz-2*dpml) in volume is replaced with size=mp.Vector3(sxy-2*dpml,sz-2*dpml) or size=mp.Vector3(sxy-2*dpml,sz-2*dpml,0), the number of sources returned by the code is 2.

This is a key point, thank you for helping find these cases. 

>The situation is similar in the Near2FarFields adjoint solver

I'll keep this in mind in the future, since the similarities should help. 

>Meanwhile, I don't see why the issue matters.

Exactly, now that I know it's expected functionality I'll close the issue. 

> You are working on Poynting flux, right? In python, you can just create FourierFields objects for relevant components, express the Poynting flux in the objective function, and the rest will be taken care of. 

Yes. I've gotten that implemented in my PR and working great in 2d. 

> The only issue is that the sizes of fields arrays may be different for different components (since they are on Yee grid), so you might need some interpolation in the objective function.

So far the only case arrays for different components have not been the same size is when the fields in that component are all zero (e.g. due to symmetry) which makes the corresponding array just a scalar zero. I also pull the array metadata to make sure the integration weights correspond to the correct meep weights. This is a really good point though, so I'll test this before I believe it works.
