### ISSUE TITLE
Animate2D update not backwards compatible, breaks tutorials

### ISSUE THREAD

**Issue by smartalecH** [NanoComp/meep#2261]
The latest `Animate2D` update (#2186) added support for TO optimization visualization (thanks @thomasdorch!). In order to do so, we had to allow the `simulation` parameter to be optional, which changed the order of the arguments. Consequently, this breaks existing code, where the position was originally `sim`,`fields`, etc. In fact, the corresponding docstring still lists the wrong order.

This is a simple fix. We can actually make the `fields` argument optional too. Then we can restore the original order for position-dependent legacy code. 

We should update the docstrings too (and add typehints if possible).

@thomasdorch do you have the bandwidth to look into this?

**Comment by smartalecH** [comment]
Hmm it seems like there are other issues too. The field animation seems broken.

**Comment by thomasdorch** [comment]
@smartalecH I'll have some time later today/this weekend to check this out. Can you post the code that's not working?

**Comment by smartalecH** [comment]
Awesome, thanks!

I'll see if I can find a suitable example I can post...

In the meantime we have a few tutorial notebooks that call the `Animate2D` class. Maybe just run those to make sure they work?

**Comment by thomasdorch** [comment]
I've had a chance to look over the code and I have a few comments:
- The `sim` argument is never used because the `__call__` method takes a `Simulation` object. From what I can tell, it was never actually used in the code, is that accurate? If so, it should probably be removed from the `Animate2D` class entirely at some point, and for now I can add a deprecation notice to the `sim` argument docstring and remove it from the examples/documentation. So far, removing the `sim` argument from all of the tutorial notebooks doesn't seem to break anything.
- I also ran into the fields not working when using mp.Ex, because the check for plotting fields is `if self.fields`, but since `mp.Ex == 0`, it doesn't plot the fields. Using `if self.fields is not None` fixes this.

**Comment by smartalecH** [comment]
> From what I can tell, it was never actually used in the code, is that accurate?

Yes I think you are right. Can you refactor and submit a PR? I'm fine with removing the unused arg so long as we have a deprecated warning and we update the tutorials if needs be. 

I believe @stevengj uses this module in a few of the notebooks for his classes too, so he might want to check those just in case (they are probably already broken due to the recent change). 

> Using if self.fields is not None fixes this.

Perfect! Nice job! Can you include this in the PR too?

**Comment by thomasdorch** [comment]
@smartalecH I've made a PR for this (#2264) and will add another commit removing the `sim` argument and printing a deprecation warning. Is a simple print statement sufficient or is there a logger somewhere that I should use?
