### ISSUE TITLE
How to establish a unidirectional plane wave with arbitrary incident angle, azimuth angle, and polarization angle?

### ISSUE THREAD

**Issue by Superwbb1999** [NanoComp/meep#2921]
As stated in the title, how to establish a unidirectional plane wave with arbitrary incident angle, azimuth angle, and polarization angle in MEEP? Can the equivalence principle be established by exciting current sources and magnetic current sources with different components? Thank you！

**Comment by mochen4** [comment]
In cylindrical coordinate, incidence at different azimuthal angles will be equivalent because of cylindrical symmetry. We can indeed use principle of equivalence to create incidence at different polar angles, and here is an [tutorial](https://meep.readthedocs.io/en/master/Python_Tutorials/Cylindrical_Coordinates/#scattering-of-sphere-with-oblique-planewave).

In 2d/3d Cartesian coordinate, you can have arbitrary incidence: https://meep.readthedocs.io/en/master/FAQ/#how-do-i-create-an-oblique-planewave-source
