### ISSUE TITLE
Feature request: Angular radiation (or scattering) pattern calculation

### ISSUE THREAD

**Issue by erikshipton** [NanoComp/meep#41]
A standard problem that computational electromagnetic tools are used for is calculating the farfield radiation pattern https://en.wikipedia.org/wiki/Radiation_pattern either from a driven element (e.g. antenna) or scattered from an object (e.g. Mie scattering or Radar Cross Section).  Meep's Near2Far calculation is helpful but its not easy to get the entire angluar (theta,phi) without extensive postprocessing.  
It would be very nice to have a feature where we specify the frequency points (for DFT), angluar resolution or number of points in theta/phi and Meep outputs an HDF5 file with theta, phi, farfield.  For example pattern(freqencies, thetas, phis) -> farfield_pattern.h5.

**Comment by oskooi** [comment]
I have added an [example](http://ab-initio.mit.edu/wiki/index.php/Meep_Tutorial/Near-to-far-field_spectra#Radiation_Pattern_of_an_Antenna) to the tutorials which shows how to set up these kinds of calculations. This involves calling the `get-farfield` routine for equally-spaced points along the circumference of a circle (in 2d). We can add a module to the libctl/Scheme interface for this feature but the user would need to be responsible for defining the near-field surface since automating that is a little tricky.

**Comment by oskooi** [comment]
For reference, a [Python version of the antenna radiation example](https://meep.readthedocs.io/en/latest/Python_Tutorials/Near_to_Far_Field_Spectra/#radiation-pattern-of-an-antenna) has also been added. the documentation
