### ISSUE TITLE
libmeepgeom link problem on MacOS

### ISSUE THREAD

**Issue by stevengj** [NanoComp/meep#660]
There seems to be some problem on MacOS (which is currently not tested on Travis) with how `libmeepgeom` was merged into `libmeep` (#630).     It builds, but when I try to run one of the test programs, for example, I get:
```sh
unixprompt$ tests/aniso_disp 
dyld: Symbol not found: _default_material
  Referenced from: /Users/stevenj/Code/meep/src/.libs/libmeep.12.dylib
  Expected in: flat namespace
 in /Users/stevenj/Code/meep/src/.libs/libmeep.12.dylib
Abort trap: 6
```
cc @ChristopherHogan

**Comment by stevengj** [comment]
Weird, the problem shows up on one of my Macs but not the other?

**Comment by ChristopherHogan** [comment]
I only have access to MacOS through Travis and was unable to reproduce the problem there, but the latest versions they have are 10.13 with Xcode 10.1.

**Comment by stevengj** [comment]
It doesn't show up on my laptop running 10.14, but it does on my 10.13 desktop at work.   Maybe I should try reinstalling in a clean directory to see if it is some weird problem from older build artifacts where it is loading the wrong library version.

**Comment by underclocked** [comment]
This was a fresh install for me on my laptop, including all dependencies (libctl, libGDSII, mpb, harminv, h5utils)

interestingly, the python module works as expected.

**Comment by underclocked** [comment]
For some reason, libctlgeom isn't included in the libraries for linking in the makefile generated from autogen.sh. Manually adding -lctlgeom to LIBS and recompiling fixes the issue for me.

**Comment by ChristopherHogan** [comment]
I was finally able to reproduce this on Travis. I found it strange that the `array_slice_ll` and `cyl_ellipsoid_ll` tests passed, but all others failed. Inspecting the binaries revealed that those two tests were linked with `libctlgeom` but the rest were not. In my case I believe it was caused by the `-dead_strip_dylibs` linker flag, which was being set by the Anaconda compilers I use to build the conda packages. This flag strips symbols it believes are not needed, but doesn't seem to understand that `default_material` (a global variable from `libctl`) will be needed at runtime. I stripped this linker flag by adding the following line to my build script:
```sh
export LDFLAGS=${LDFLAGS/-Wl,-dead_strip_dylibs/}
```
And everything worked fine. Interestingly, if you try to set `default_material` in one of the failing tests while this flag is set, it realizes it needs to link with `libctlgeom` and everything works fine. Also, setting `LIBS="-lctlgeom $LIBS"` was not enough for me; it still refused to link with `libctlgeom`. I'll proably make a PR to add `-lctlgeom` to `LIBS` anyway, because that seems correct. 

The only thing I don't fully understand is why the error message complains about `_default_material` with an underscore. The `libctl` global has no underscore, and the only place that symbol appears in meep or libctl is as a parameter to `set_materials_from_geometry`, which runs `default_material = _default_material`.
