### ISSUE TITLE
get_farfields routine to obtain far fields as NumPy array

### ISSUE THREAD

**Issue by oskooi** [NanoComp/meep#680]
Currently, there are only two routines available for obtaining the [far fields](https://meep.readthedocs.io/en/latest/Python_User_Interface/#near-to-far-field-spectra): 

1. `get_farfield`: returns the far field at a single point
2. `output_farfields`: writes the far fields in a given [`Volume`](https://meep.readthedocs.io/en/latest/Python_User_Interface/#volume) to an HDF5 file 

It would be useful to have an additional third routine which returns the far fields in a given `Volume` as a NumPy array. This would facilitate post processing directly from within a single Python script without having to write and read from disk.

As an extension of this feature, rather than restrict the far field output to a rectilinear `Volume`, the region could be generalized to a [`GeometricObject`](https://meep.readthedocs.io/en/latest/Python_User_Interface/#geometricobject) (e.g., `Sphere`, `Prism`, `Cylinder`, etc.)

**Comment by stevengj** [comment]
Looks straightforward, because the [`dft_near2far::save_farfields`](https://github.com/NanoComp/meep/blob/cfef8f199ff788367e5a55a8a41379efe558ebe6/src/near2far.cpp#L262-L335) function already collects all the necessary information in an array before writing it to disk.  So we would want to:

1. Refactor `save_farfields` into two routines — a `get_farfields_array` that collects the `EH` array and a `save_farfields` that calls `get_farfields_array` and then saves it to HDF5.

2. Change `get_farfields_array` to use `sum_to_all` instead of `sum_to_master` so that all processes get the data.

3. Make a high-level wrapper around `get_farfields_array` and call it from Python.
