### ISSUE TITLE
get_field_point does not support parallel use

### ISSUE THREAD

**Issue by oskooi** [NanoComp/meep#685]
The [current implementation](https://github.com/NanoComp/meep/blob/master/src/monitor.cpp#L198-L219) of [`get_field_point`](https://meep.readthedocs.io/en/latest/Python_User_Interface/#field-computations) does not include parallel support (i.e., MPI). A workaround involving `integrate_field_function` was previously proposed by @stevengj in the [mailing list](https://www.mail-archive.com/meep-discuss@ab-initio.mit.edu/msg04548.html) but has yet to be implemented.

**Comment by stevengj** [comment]
This should be as easy as adding an [`is_mine` check to `fields::get_field(component, ivec)`](https://github.com/NanoComp/meep/blob/a5308c11167503fcfff5467af739ecef583bebbc/src/monitor.cpp#L169-L179) and then putting a `sum_to_all` at the end.

I would add a `bool parallel=true` optional third argument so that the caller can turn off the `sum_to_all`.  The reason is that the `vec` version [`fields::get_field(component, vec)`](https://github.com/NanoComp/meep/blob/a5308c11167503fcfff5467af739ecef583bebbc/src/monitor.cpp#L169-L179) calls the `ivec` version 8 times and then performs a weighted average, so we will want to call the `ivec` version with `parallel=false` and then do the `sum_to_all` only once on the weighted average at the end.
