### ISSUE TITLE
"um_scale" incorrectly used for some materials

### ISSUE THREAD

**Issue by 98md21** [NanoComp/meep#706]
Various materials (e.g., c-Si and a-Si) have "um_scale" in the denominator of their "frq" and "gam" expressions. Based on the instructions for using "um_scale" in [https://meep.readthedocs.io/en/latest/Materials/#materials-library], "um_scale" should be in the numerator of the "frq" and "gam" expressions.

**Comment by oskooi** [comment]
As described in [materials library](https://meep.readthedocs.io/en/latest/Materials/#materials-library), the units of the frequency and decay-rate fitting parameters for the Lorentzian susceptibility terms is 1/µm. There is no standard convention used in the references for the units of these parameters: some use e.g. eV while others use 1/µm. (Some references provide the *wavelength* in µm rather than the frequency.) For example, the parameters for crystalline silicon (c-Si), provided in p. 775 of [J. Optical Society of America A, Vol. 28, pp. 770-777, 2011](http://fdtd.kintechlab.com/_media/deinega_-_minimizing_light_reflection_from_dielectric_textured_surfaces.pdf) are in units of 1/µm. The parameters for the elemental metals (Al, Ag, Au, etc.) from [Applied Optics, Vol. 37, pp. 5271-83, 1998](https://www.osapublishing.org/ao/abstract.cfm?uri=ao-37-22-5271) are in eV.

Depending on the units, these terms are multiplied by either `eV_um_scale` or 1/`um_scale` so that everything is defined in units of 1/µm. This way, if you want to redefine your unit length to e.g. 1 nm, you would need to add the line `um_scale = 1e-3 * um_scale` to the materials library and all the units are rescaled appropriately.

**Comment by 98md21** [comment]
Dear Ardavan Oskooi,

Thank you for your detailed reply. However, I respectfully disagree and would like you to consider the following for the sake of having the code correct for others. 

In your example of redefining the unit length to 1 nm, frequency and decay-rate parameters would increase by 1000, which is incorrect given that unit length decreases. In fact, when I used the material `Au_JC_visible`, I got NaN-like values for field amplitudes until I moved `um_scale` to the numerator. Furthermore, to get to the root of the problem, `eV_um_scale` is defined in `materials.py` with `um_scale` in the _numerator_, i.e., frequencies/decay-rates defined with  `eV_um_scale` are _not_ defined in units of 1/um. In other words, the definition of  `eV_um_scale` and the usage of `um_scale` in frequency/decay-rate expressions are inconsistent and should be corrected accordingly. 

Thank you in advance for your further consideration.

**Comment by oskooi** [comment]
If your fields are blowing up when you reduce the unit length then you will likely need to increase the `resolution` or reduce the `Courant` factor as described in this [FAQ](https://meep.readthedocs.io/en/latest/FAQ/#why-are-the-fields-blowing-up-in-my-simulation).
