### ISSUE TITLE
On WSL, coufigure meep got two errors: could not find hdf5 and linking to guile failed

### ISSUE THREAD

**Issue by genlintan** [NanoComp/meep#797]
I installed Windows Subsystem for Ubuntu, and re-configureed meep and Mpb, but got:
(1) could not find HDF5 library! switch  to -without-hdf5
   In fact, hdf is at /usr/local/hdf5 ( Tis is installed by me)
(2) Configure error : linking to guile failed
 In fact, it is in /usr/share/guile/2,2 ( This is Ubuntu's pkg installed)

How to fix it?
Thank you for your help

**Comment by stevengj** [comment]
You have to tell the configure script where to find packages if you installed them in nonstandard locations.  For example, if you installed HDF5 in `/usr/local/hdf5 `, I assume that you mean that libhdf5 is in `/usr/local/hdf5/lib` and `hdf5.h` is in `/usr/local/hdf5/include`, right?  In that case you would need to `./configure LDFLAGS="-L/usr/local/hdf5/lib" CPPFLAGS="-I/usr/local/hdf5/include"` to tell the compiler where to find these.

See the "Unix installation basics" section in https://meep.readthedocs.io/en/latest/Build_From_Source/

(Unless you mean that `/usr/local/hdf5` is the *source* directory? You have to run `make install` after you compile things in order to install them.)
