### ISSUE TITLE
speeding up near2far

### ISSUE THREAD

**Issue by stevengj** [NanoComp/meep#861]
Two options:

- [x] use `#pragma omp parallel for` in `farfield_lowlevel`, maybe by moving `for (int i = 0; i < Nfreq; ++i)` to be the outermost loop.  This only works if you have cores to spare and we compile with OpenMP. #868

- [x] in 2d, we can switch to a faster Bessel-function calculation.   In a quick test, ~~the [Fortran routines by Amos](https://people.sc.fsu.edu/~jburkardt/f77_src/toms644/toms644.html)~~ libc `jn` and `yn` routines are about 4-5x faster than the ones in GSL.  Precompiled binaries of these are available in https://github.com/JuliaMath/openspecfun at https://github.com/JuliaMath/OpenspecfunBuilder/releases, for example, if we don't want to require a Fortran compiler. #869

For the first option, would be nice to try it out.  Note that you will need to compile with `-fopenmp`

**Comment by stevengj** [comment]
I added a branch `omp_near2far` with the changed loop (871b4ca06d22d54dd7e9fe7717c37e7fe6687fd7).  You will need to manually add the `-fopenmp` flag by configuring
```
./configure CXX="g++ -fopenmp"
```
or similar

**Comment by oskooi** [comment]
This seems to be working and giving rise to linear speedup as demonstrated in the figure below. The test involves timing the `get_farfields` calculations in [`python/examples/binary_grating_n2f.py`](https://github.com/NanoComp/meep/blob/master/python/examples/binary_grating_n2f.py) involving 21 frequencies and 500 points for 5 values of `OMP_NUM_THREADS` (1-5) for two cases: (1) a unit cell with `add_near2far` involving `nperiods=20` and (2) a super cell with 41 unit cells and `nperiods=1` (i.e., default: no tiling). Note: since the total time for `get_farfields` is not yet directly available, pending #856, the values were computed by subtracting from the "Elapsed run time" all the components in "Field time usage" (e.g., "time stepping, "communicating", etc).

![n2f_openmp_semilogy](https://user-images.githubusercontent.com/7152530/57340770-16493500-70ec-11e9-8360-da92244e2509.png)

The only unusual thing was that it worked for the serial version (i.e., `CXX="g++ -fopenmp"`) but *not* with the OpenMPI compiler (i.e., `CXX="mpic++ -fopenmp"`).

**Comment by stevengj** [comment]
If you use MPI, you need to set `MPICXX` because of [this file](https://github.com/NanoComp/meep/blob/4051db54fc26e816af1a0babda77019231427924/configure.ac#L33)

**Comment by stevengj** [comment]
Actually, the Fortran Amos routines are just for complex arguments, which we don't need.  For real arguments and integer order, Julia is using the [POSIX bessel functions](http://pubs.opengroup.org/onlinepubs/9699919799/functions/j0.html), which we should use too.
