### ISSUE TITLE
Polarization and k-vector of a plane wave/Gaussian source 

### ISSUE THREAD

**Issue by zemmyang** [NanoComp/meep#971]
For example, if I have a 3D space with nothing but a plane wave, or a Gaussian source, how do I define that I want that source to be propagating along the x-axis and polarized along the z-axis (for example). I've been trying to change `component`, but it doesn't appear to help. 

For the Gaussian beam, I'm basically trying to get something like this: https://en.wikipedia.org/wiki/Gaussian_beam#/media/File:Gaussian_beam_w40mm_lambda30mm.png

I also saw an example for a plane wave in homogeneous media (https://meep.readthedocs.io/en/latest/Python_Tutorials/Eigenmode_Source/#eigenmode-source), but it appears to be a periodic structure. My simulation doesn't have the same periodicity.

**Comment by smartalecH** [comment]
Here's a 2D example that launches a "gaussian beam" polarized in the Z direction (it's a 2D TE mode) in the +X direction.

```python
import meep as mp
import numpy as np
from matplotlib import pyplot as plt

resolution = 10 # pixels/μm

sx = 14
sy = 10
sz = 0
cell_size = mp.Vector3(sx,sy,sz)

pml_layers = [mp.PML(thickness=2)]

# rotation angle (in degrees) of planewave, counter clockwise (CCW) around z-axis
rot_angle = np.radians(0)

fsrc = 1.0 # frequency of planewave (wavelength = 1/fsrc)

n = 1.5  # refractive index of homogeneous material
default_material = mp.Medium(index=n)

k_point = mp.Vector3(fsrc*n)

# beam waist
w = 0.6

def amp_func(pt):
    return 1/ np.sqrt(np.pi*w**2) * np.exp(-pt.y ** 2 / w ** 2)

sources = [mp.EigenModeSource(src=mp.GaussianSource(fsrc,fwidth=0.1*fsrc),
                              center=mp.Vector3(),
                              size=mp.Vector3(y=sy),
                              direction=-mp.X,
                              eig_kpoint=k_point,
                              eig_band=1,
                              eig_parity=mp.EVEN_Y+mp.ODD_Z,
                              amp_func=amp_func,
                              eig_match_freq=True)]

sim = mp.Simulation(cell_size=cell_size,
                    resolution=resolution,
                    boundary_layers=pml_layers,
                    sources=sources,
                    default_material=default_material)

sim.run(until=60)

# plot the intenisty
f = lambda x: np.abs(x) ** 2
field_parameters = {'post_process':f}
sim.plot2D(fields=mp.Ez,field_parameters=field_parameters)
plt.savefig('gaussian_beam.png')
```

![gaussian_beam](https://user-images.githubusercontent.com/24902086/61546350-a5d16500-aa06-11e9-8a9a-13af370743a5.png)

You can scale it to 3 dimensions without too much hassle, just make sure you pick the right eigenmode to launch. If you want to launch the beam in both directions (like your Wikipedia image), then you can use two sources and rotate one of the sources 180 degrees. Keep in mind that there will be some weird interference with this approach, however, due to the backpropagating artifacts of the two sources (you can see the artifacts in the image above).

A lot of papers I've read involving computational gaussian beam experiments tend to only care about one direction, however (i.e. for scattering problems). It all depends on your application.

**Comment by stevengj** [comment]
The [FAQ](https://meep.readthedocs.io/en/latest/FAQ/#how-do-i-create-a-focused-beam-with-a-gaussian-envelope) partially addresses this.

Closing this issue in favor of #1094, which describes a way to implement a more general Gaussian source.
