### ISSUE TITLE
How to compute the voltage induced on a dipole antenna?

### ISSUE THREAD

**Issue by athulshaji** [NanoComp/meep#986]
Hello,

I am interested in finding the voltage induced on a wire dipole antenna ( a 2D problem). Suppose the source is radiating a Gaussian pulse of particular field strength. When this wave falls on the antenna a voltage is induced. How to calculate the induced voltage using MEEP?

Can **integrate_field_function** be used along the direction of interest (either X or Y assuming Ex or Ey field respectively) by specifying the start and endpoints of integration? Is this the way to solve this problem?

Looking forward to the reply.

Thank you,
Regards,
Athul Shaji

**Comment by stevengj** [comment]
Yes, you can specify a 1d volume to `integrate_field_function` in order to compute a line integral (along the x, y, or z direction).  There is actually an example of this in the manual:

https://meep.readthedocs.io/en/latest/Field_Functions/

If you are modeling the antenna explicitly as a conductor, you might instead integrate the current density σE to find the average current flowing through the conductor, and back out an effective voltage from that.  This way you will account for the skin effect and other complications of fullwave electromagnetism.
